### ISSUE TITLE
保存格式化时，对于函数内的 local 变量无法格式化到。

### ISSUE THREAD

**Issue by Gowa2017** [CppCXY/EmmyLuaCodeStyle#1]
<img width="971" alt="图片" src="https://user-images.githubusercontent.com/33367355/151495590-95fdc605-2233-4360-abc7-17302c978165.png">

比如，那个等号，就会显示还应该对齐。
进行二次格式化就可以。

**Comment by CppCXY** [comment]
单次格式化无法一次性到位，这是由于对齐到等号这个行为很难合理的界定格式化后的合理位置，以后修改。
