### ISSUE TITLE
`duplicate-set-field` is reading from CoreLibs even though `diagnostics.libraryFiles` is set to 'Disable'

### ISSUE THREAD

**Issue by edzillion** [CppCXY/EmmyLuaCodeStyle#100]
Hi

Thanks for this plugin. I am getting warning for `duplicate-set-field` on this line:

`function playdate.update()`

and the duplicate is in the `CoreLibs` folder here:

`...\PlaydateSDK\CoreLibs\__stub.lua`

I have set the CoreLibs folder to be ignored by the code checker:

`"Lua.diagnostics.libraryFiles": "Disable",`

Is this the expected behaviour?

**Comment by CppCXY** [comment]
my plugin does not have this feature. please go to Sumneko Lua issue for questions

**Comment by edzillion** [comment]
ok will do thanks
