### ISSUE TITLE
trailing_table_separator when strings is last row

### ISSUE THREAD

**Issue by MeiramSh** [CppCXY/EmmyLuaCodeStyle#104]
I think I found wrong behavior.
When `trailing_table_separator` is `always`,  I think it should insert comma here
```lua
local t = {
  a = 'a' -- <- here
}
```
So it should become
```lua
-- expected behavior
local t = {
  a = 'a',
}
```
But it doesn't happen
```lua
-- actual behavior
local t = {
  a = 'a'
}
```

NOTE: it always works except when the last element is string and is surrounded with `'` or `"`
```lua
local t = {
  a = {},
}

local t1 = {
  a = 0,
}

local t2 = {
  a = true,
}

-- it even works here
local t3 = {
  a = [[here]],
}
```

**Comment by kosorin** [comment]
I have the same problem in https://github.com/LuaLS/lua-language-server/issues/2045#issue-1649652364

I found out that the problem is caused by the `quote_style`:

```
[*.lua]
trailing_table_separator = smart
quote_style = double
```
```lua

local foo = {
    "bar"
}
```

It works without this option:


```
[*.lua]
trailing_table_separator = smart
```
```lua

local foo = {
    "bar",
}
```
