### ISSUE TITLE
包含中文的表格对齐能否优化一下, 感觉还是有点问题

### ISSUE THREAD

**Issue by xiangnanscu** [CppCXY/EmmyLuaCodeStyle#107]
格式化后是这样的:
```lua
local Test = Model {
  table_name = 'test',
  fields = {
    { name = 'avatar', label = "头像",       size = '4m' },
    { name = 'avatar', label = "头像啊啊", size = '4m' },
  }
}
```
为啥`"头像",`后面是7个空格而` "头像啊啊",`是1个空格呢?

**Comment by CppCXY** [comment]
这里面主要是的原因是unicode 字符我按字节数的长度

**Comment by CppCXY** [comment]
代码中一般很少出现中文,如果你不希望这里有问题可以加上---@format disable-next

**Comment by CppCXY** [comment]
对于涉及到中文的对齐, 你可以想一个合适的方案, 或者直接PR

**Comment by xiangnanscu** [comment]
看到C艹就麻了, 我选择`---@Format disable-next`.

**Comment by xiangnanscu** [comment]
@CppCXY 大神, 我又来了.  考虑到主流的等宽字体文件(比如更纱,ubuntu mono之类的)都是按1中文宽度等于2英文宽度来设置的, 在处理中文的时候, 能否不要按字节数的长度, 使用固定的2来弄? 这样就能对齐了!

**Comment by CppCXY** [comment]
说得好, 那么就你来实现吧

**Comment by xiangnanscu** [comment]
@CppCXY 能不能指导一下, 按字节数确定空格数的代码块在哪?

**Comment by CppCXY** [comment]
我建议是遇到Unicode 字符就放弃对齐, 相关代码在AlignAnalyzer.cpp

**Comment by CppCXY** [comment]
考虑到非中文的Unicode字符大小可能又不太一样, 所以我建议检查到Unicode字符就放弃对齐, 算了我自己来做.
