### ISSUE TITLE
希望表操作符中的+号不添加额外的空格

### ISSUE THREAD

**Issue by Philofallever** [CppCXY/EmmyLuaCodeStyle#108]
1. 希望开启操作符空白后 ,表操作符中的+号不添加额外的空格
![image](https://github.com/CppCXY/EmmyLuaCodeStyle/assets/15180187/e4b189f6-ca57-4662-a762-d5baf90fb844)

**Comment by CppCXY** [comment]
设置 space_around_table_append_operator = true

**Comment by Philofallever** [comment]
好的 感谢已解决

另外问下怎么用lua server插件配置 stylecheck

**Comment by CppCXY** [comment]
其中name-style-check对当前的Lua ls不可用

**Comment by Philofallever** [comment]
好吧 写了 就是发现命名没地方配 😢

**Comment by CppCXY** [comment]
name-style才刚合并进去, 还没发布, 最近作者躺尸在家,估计要下个月了
