### ISSUE TITLE
[Question] How do I prevent removing empty lines after comment

### ISSUE THREAD

**Issue by FlashHit** [CppCXY/EmmyLuaCodeStyle#109]
The issue that I am having is that this:
```lua
--[[
some comment
--]]

local x = 0
```
will get formated to:
```lua
--[[
some comment
--]]
local x = 0
```
while:
```lua
-- some comment

local x = 0
```
will stay as it is.

I want that this stays as it is as well:
```lua
--[[
some comment
--]]

local x = 0
```

So how do I prevent it from removing that empty line?

Also in general it would be nice to have examples for each setting in `lua.template.editorconfig` so I can see what each setting does.

**Comment by FlashHit** [comment]
Another question:
how do I prevent it from aligning comments?
```lua
UserRoleFlags = {
	CanSpeak = 1 << 0, -- 1
	CanMovePlayers = 1 << 1, -- 2
	CanKillPlayers = 1 << 2, -- 4
	CanKickPlayers = 1 << 3, -- 8
	CanTemporaryBanPlayers = 1 << 4, -- 16
	CanPermanentlyBanPlayers = 1 << 5, -- 32
	CanEditGameAdminList = 1 << 6, -- 64
	CanEditBanList = 1 << 7, -- 128
	CanEditMapList = 1 << 8, -- 256
	CanUseMapFunctions = 1 << 9, -- 512
	CanAlterServerSettings = 1 << 10, -- 1024
	CanEditReservedSlotsList = 1 << 11, -- 2048
	CanEditTextChatModerationList = 1 << 12, -- 4096
	CanShutdownServer = 1 << 13 -- 8192
}
```
gets formatted to this:
```lua
UserRoleFlags = {
	CanSpeak = 1 << 0,                    -- 1
	CanMovePlayers = 1 << 1,              -- 2
	CanKillPlayers = 1 << 2,              -- 4
	CanKickPlayers = 1 << 3,              -- 8
	CanTemporaryBanPlayers = 1 << 4,      -- 16
	CanPermanentlyBanPlayers = 1 << 5,    -- 32
	CanEditGameAdminList = 1 << 6,        -- 64
	CanEditBanList = 1 << 7,              -- 128
	CanEditMapList = 1 << 8,              -- 256
	CanUseMapFunctions = 1 << 9,          -- 512
	CanAlterServerSettings = 1 << 10,     -- 1024
	CanEditReservedSlotsList = 1 << 11,   -- 2048
	CanEditTextChatModerationList = 1 << 12, -- 4096
	CanShutdownServer = 1 << 13           -- 8192
}
```
and I don't want that.

**Comment by CppCXY** [comment]
> Another question: how do I prevent it from aligning comments?
> 
> ```lua
> UserRoleFlags = {
> 	CanSpeak = 1 << 0, -- 1
> 	CanMovePlayers = 1 << 1, -- 2
> 	CanKillPlayers = 1 << 2, -- 4
> 	CanKickPlayers = 1 << 3, -- 8
> 	CanTemporaryBanPlayers = 1 << 4, -- 16
> 	CanPermanentlyBanPlayers = 1 << 5, -- 32
> 	CanEditGameAdminList = 1 << 6, -- 64
> 	CanEditBanList = 1 << 7, -- 128
> 	CanEditMapList = 1 << 8, -- 256
> 	CanUseMapFunctions = 1 << 9, -- 512
> 	CanAlterServerSettings = 1 << 10, -- 1024
> 	CanEditReservedSlotsList = 1 << 11, -- 2048
> 	CanEditTextChatModerationList = 1 << 12, -- 4096
> 	CanShutdownServer = 1 << 13 -- 8192
> }
> ```
> 
> gets formatted to this:
> 
> ```lua
> UserRoleFlags = {
> 	CanSpeak = 1 << 0,                    -- 1
> 	CanMovePlayers = 1 << 1,              -- 2
> 	CanKillPlayers = 1 << 2,              -- 4
> 	CanKickPlayers = 1 << 3,              -- 8
> 	CanTemporaryBanPlayers = 1 << 4,      -- 16
> 	CanPermanentlyBanPlayers = 1 << 5,    -- 32
> 	CanEditGameAdminList = 1 << 6,        -- 64
> 	CanEditBanList = 1 << 7,              -- 128
> 	CanEditMapList = 1 << 8,              -- 256
> 	CanUseMapFunctions = 1 << 9,          -- 512
> 	CanAlterServerSettings = 1 << 10,     -- 1024
> 	CanEditReservedSlotsList = 1 << 11,   -- 2048
> 	CanEditTextChatModerationList = 1 << 12, -- 4096
> 	CanShutdownServer = 1 << 13           -- 8192
> }
> ```
> 
> and I don't want that. if I would want that then it should be tab spaces as well instead of normal spaces.


set `align_continuous_inline_comment = false`

**Comment by CppCXY** [comment]
> The issue that I am having is that this:
> 
> ```lua
> --[[
> some comment
> --]]
> 
> local x = 0
> ```
> 
> will get formated to:
> 
> ```lua
> --[[
> some comment
> --]]
> local x = 0
> ```
> 
> while:
> 
> ```lua
> -- some comment
> 
> local x = 0
> ```
> 
> will stay as it is.
> 
> I want that this stays as it is as well:
> 
> ```lua
> --[[
> some comment
> --]]
> 
> local x = 0
> ```
> 
> So how do I prevent it from removing that empty line?
> 
> Also in general it would be nice to have examples for each setting in `lua.template.editorconfig` so I can see what each setting does.

currently this is a bug,  each option have a demo that requires the most intensive work, maybe you can go to the [test](https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/Test/src/FormatStyle_unitest.cpp)

**Comment by FlashHit** [comment]
Thanks
