### ISSUE TITLE
snake_case doesn't support numbers in names

### ISSUE THREAD

**Issue by GiuseppeIII** [CppCXY/EmmyLuaCodeStyle#113]
Snake_case doesn't seem to support numbers in names. See below for example:
<img width="572" alt="Screenshot_1" src="https://github.com/CppCXY/EmmyLuaCodeStyle/assets/33046979/de9444a4-a4b0-4b2c-a2ea-45760102e612">

**Comment by CppCXY** [comment]
because I think he should be `team1_id`, or you can add it to the ignore list, or you can use regular expressions

**Comment by GiuseppeIII** [comment]
👍 For anyone else viewing this who is okay with numbers in their snake_case this pattern should work: 
```
{
      "type" : "pattern",
      "param": "^(?:[a-z0-9]+_)*[a-z0-9]+$"
}
```
