### ISSUE TITLE
Name Style Descriptions

### ISSUE THREAD

**Issue by GiuseppeIII** [CppCXY/EmmyLuaCodeStyle#114]
Would it be possible to get some details on what each name_style refers to
```
local_name_style
function_param_name_style
function_name_style
local_function_name_style
table_field_name_style
global_variable_name_style
module_name_style
require_module_name_style
class_name_style
```

I had assumed `class_name_style` refered to classes as annotated with `@class` but it doesn't seem to do anything.

**Comment by CppCXY** [comment]
`class_name_style` mean like `local a = class("a")`

**Comment by GiuseppeIII** [comment]
Is `class` some third party thing?

**Comment by CppCXY** [comment]
It's not from some third-party library, which is the usual name for functions that emulate OOP in Lua

**Comment by GiuseppeIII** [comment]
👍 Interesting, thanks for info 😄
