### ISSUE TITLE
Unlimited line length

### ISSUE THREAD

**Issue by GiuseppeIII** [CppCXY/EmmyLuaCodeStyle#115]
Is there a way to set the max_line_length to be unlimited?

Currently, even if the max_line_length is undefined. The code will get reformated to 120 chars long. I can obsviously just set this value super high, but I would rather not have a limit at all.

**Comment by CppCXY** [comment]
set `max_line_length=unset` but it mean length = 998

**Comment by GiuseppeIII** [comment]
Would there be any way for it to actually just not check for the line length at all?

**Comment by CppCXY** [comment]
Currently no, and the line width is intended to have no performance impact, my algorithm is very fast, and the current style check does not check the line width
