### ISSUE TITLE
Spell Check Issues

### ISSUE THREAD

**Issue by GiuseppeIII** [CppCXY/EmmyLuaCodeStyle#118]
The current spell check system seems to have some issues around special characters, where it is not able to correctly figure out the bounds of the words.
<img width="281" alt="Screenshot_1" src="https://github.com/CppCXY/EmmyLuaCodeStyle/assets/33046979/df19b26f-45c4-43f7-8c1c-b4c113ea73c5">
<img width="361" alt="Screenshot_2" src="https://github.com/CppCXY/EmmyLuaCodeStyle/assets/33046979/73987667-6b46-4f7f-89b6-e9a5af846c6a">
<img width="46" alt="Screenshot_3" src="https://github.com/CppCXY/EmmyLuaCodeStyle/assets/33046979/841eeec7-74d9-409a-bd70-4e2101df11b1">
<img width="63" alt="Screenshot_4" src="https://github.com/CppCXY/EmmyLuaCodeStyle/assets/33046979/d1340eba-e5be-4135-8dfa-46a84521d4b2">

It also seems that only a british dictionary is being used for the spelling, so that very common American spellings of words show up as being incorrect. Is there anyway way to add dictionaries?

**Comment by CppCXY** [comment]
you can make a pr to resources/dictionary and modify the spell check algorithm at CodeFormatCore/CodeSpellChecker
