### ISSUE TITLE
Request for supporting the new syntax

### ISSUE THREAD

**Issue by VVeaz** [CppCXY/EmmyLuaCodeStyle#119]
I'm creating this issue after discussion in the LuaLS/lua-language-server repository - https://github.com/LuaLS/lua-language-server/issues/2165 .

I'm using lua LSP in my own React Monaco Editor client.

I have a plugin for my own syntax, it is that the notation {@WordD_123} is equivalent to "WorD_123". Word_123 can consist of letters, numbers and '_'. I am attaching the file with this plugin.
[plugin.txt](https://github.com/CppCXY/EmmyLuaCodeStyle/files/11814010/plugin.txt)

Currently, if the user uses this syntax, he cannot format the code. 
I understood the conversation in such a way that here I can ask for support for my syntax in formatting.
So I hereby kindly ask you to support my syntax.

**Comment by CppCXY** [comment]
You mean your identifiers support the @ symbol, is there anything else?

**Comment by VVeaz** [comment]
I mean that the {@token} should be treated as an equivalent to 'token'

For "token" the notatation is {@token} so I can write 
`local a = {@token}`
and now formater does not work.

**Comment by CppCXY** [comment]
the syntax is very strange and too similar to Lua's table expressions. I'm curious why it isn't using the '@symbol'.

**Comment by VVeaz** [comment]
We have a big code base with legacy syntax like that. I cannot really determine why this was chosen but i'm stuck with it anyway.

**Comment by CppCXY** [comment]
I accept this reasoning, and it may take until tonight to implement.

**Comment by CppCXY** [comment]
I completed this feature a few days ago, but it hasn't been updated to Sumneko Lua that quickly. You can fork the Lua Ls project yourself and update this submodule separately, then compile it using luamake.

**Comment by VVeaz** [comment]
We did as you advised, thank you very much.
