### ISSUE TITLE
Feature Suggestion/Request: Rule for semicolons

### ISSUE THREAD

**Issue by AndreaWalchshoferSCCH** [CppCXY/EmmyLuaCodeStyle#120]
As Lua allows, but not requires semicolons to end a statement, this might lead to an inconsistent code style.
That's why the idea is to provide a rule for semicolons to end statements ("end_statement_with_semicolon"?).
Possible options I thought of are:
- `keep`, so same behaviour as currently
- `never`, so no statement is ended with a semicolon (also meaning, no multiple statements per line) - this is the one I'd need
- `always`, so every statement is ended with a semicolon (similar to e.g. C syntax)
- `same_line`, so only to separate multiple statements that were put on the same line

Is this something you'd be willing to integrate into this formatter?

**Comment by CppCXY** [comment]
however, removing the semicolon does not produce an equivalent semantic. For example:
```lua
local t = p; -- if the semicolon is removed here, it turns from two statements into one statement.
("2%d"):format(123)
```

**Comment by AndreaWalchshoferSCCH** [comment]
But e.g. 
```
print(x);
print(y);
```
and
```
print(x)
print(y)
```
should be equivalent, and
```
print(x); print(y);
```
could also just be turned into the second version.


Would you expect a rule for things like that too complicated because of examples like yours, or could those be handled with appropriate effort?

**Comment by AndreaWalchshoferSCCH** [comment]
Yes, I will look into it and give it a go.
Thank you for your feedback on the feasibility and and the potential problems! :)

**Comment by CppCXY** [comment]
Is there any progress or difficulty? I understand that it can be very challenging to understand my code. If it's too difficult, I can implement it myself.

**Comment by AndreaWalchshoferSCCH** [comment]
I've started by adding the configuration properties and have yet to implement the rule. It might take me a few more days as it doesn't have the highest priority on my list, but I'm working on it :)

**Comment by AndreaWalchshoferSCCH** [comment]
Thank you for your help and feedback in the PR!
I just want to add, once I understood the structure of the project and how it works, it was really nice to work with it and quite clear where changes needed to be made. So, thank you also for this project!

**Comment by CppCXY** [comment]
Thank you. In fact, I have written three versions of the Lua formatter before version 1.0.0, each with different approaches. I also lost a lot of hair in the process. 

Starting from version 1.0.0, I redesigned everything from the parser and identified the core issues that need to be addressed in code formatting, as well as scalability concerns. 

If you have seen other formatting implementations, you will notice that the majority of them handle each node individually during a single traversal. When there are multiple formatting features, the logic becomes very complex, and different formatting requirements often conflict with each other. It becomes extremely difficult to make modifications when the project grows larger. as a result, most formatters tend to be 'opinionated' in their choices. the previous versions of my formatter were indeed implemented in a similar manner. 

However, my current implementation is not perfect either, and there are some aspects that I'm not entirely satisfied with. Therefore, I have chosen to set aside those concerns for now and wait for the right time to refactor the code.
