### ISSUE TITLE
insert_final_newline 这个格式化选项没用 无法关闭

### ISSUE THREAD

**Issue by NeoRrrr** [CppCXY/EmmyLuaCodeStyle#129]

**Comment by CppCXY** [comment]
如果设置为false 格式化检查都能检查出来
![image](https://github.com/CppCXY/EmmyLuaCodeStyle/assets/40318218/8eb89eac-64c9-4e1e-bb5e-02c3874dc248)
格式化结果是这样的
![image](https://github.com/CppCXY/EmmyLuaCodeStyle/assets/40318218/b2c3699c-afab-4ce3-8b94-aa7dfabd4fd9)
你用的什么插件, 什么平台, 什么版本
