### ISSUE TITLE
链式调用时，允许在冒号后面带个空格

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#13]
![image](https://user-images.githubusercontent.com/5213431/154057016-f2e054e5-ca7f-4299-b1fd-506db328a000.png)

**Comment by CppCXY** [comment]
那么这个原则会导致:
```lua
aaaaa: bbbb(): ddddddddd(): cccccccccccc()
```
或者说希望是这样:
```lua
aaaaa:bbbb()
    : ddddddddd():cccccccccccc()
    : eeeeeeee():ffffffffffff()
```

**Comment by sumneko** [comment]
我仔细想了一下，其实很多时候格式化的期望和诊断的期望并不一致，诊断一般会更加宽松一些。
比如说对齐，如果格式化的时候能帮我对齐自然是最好的，但是我没有对齐也无所谓，不需要帮我诊断这个。

其实这里也是一样的，在比较特别的写法里（比如一个表达式但却分成了多行），我写不写空格不需要帮我诊断，格式化的时候尊重就行。

你上面的2个例子里，第一个写法要诊断，因为是写在一行里的；第二个写法不诊断，因为是有了比较特别的写法，由编写者自己决定如何排版。

**Comment by CppCXY** [comment]
这里可以被归纳为对齐特性，长链式表达式在垂直方向允许对齐
