### ISSUE TITLE
添加等号两边要不要空格的设置

### ISSUE THREAD

**Issue by MrZ626** [CppCXY/EmmyLuaCodeStyle#135]
翻了一圈文档没看到怎么关掉等号两边的空格，应该是没有吧，可以加一下？我个人习惯除了保留字旁边都不要空格的

**Comment by CppCXY** [comment]
很少见到这种方式, 有什么理由吗.

**Comment by MrZ626** [comment]
毕竟现在数学运算符两旁都能选，函数和table相关的小中大括号前后都能调，那给等于号加一个也可以理解吧
我自己目前的习惯是有且只有英文关键字两旁加空格，其他全都不要，原因是以前在便携设备上写的，屏幕空间有限，所以空格能省就省，甚至以前连关键字旁如果有括号或者引号都不空，像`if(a)==b[1]then`这样

**Comment by MrZ626** [comment]
哦对，除了赋值，一堆比较运算符也可以合并起来加个选项

**Comment by CppCXY** [comment]
目前新增了两个选项`space_around_assign_operator = false`和`space_around_logical_operator = false`可以基本达到要求, 等以后发布了就可以用了.
