### ISSUE TITLE
Repeated application of formatting results in behavior change

### ISSUE THREAD

**Issue by ddickstein** [CppCXY/EmmyLuaCodeStyle#136]
I have the following line in a Lua file:
```lua
local opts = { on_exit = function() job = nil end }
```
Saving once produces:
```lua
local opts = { on_exit = function()
job = nil end }
```
Saving again produces:
```lua
local opts = { on_exit = function()
  job = nil
end }
```
I don't think it should be possible to get a different result by reapplying formatting.

Separately, is there a way to allow single-line anonymous functions like the original line?

My `.editorconfig`:
```
[*.lua]
align_array_table=true
align_call_args=false
align_chain_expr=none
align_continuous_assign_statement=true
align_continuous_inline_comment=false
align_continuous_line_space=2
align_continuous_rect_table_field=true
align_continuous_similar_call_args=true
align_function_params=false
align_if_branch=false
auto_collapse_lines=true
break_all_list_when_line_exceed=true
break_before_braces=false
call_arg_parentheses=keep
continuation_indent=2
detect_end_of_line=false
end_of_line=lf
end_statement_with_semicolon=never
ignore_space_after_colon=false
ignore_spaces_inside_function_call=false
indent_size=2
indent_style=space
insert_final_newline=true
keep_indents_on_empty_lines=false
line_space_after_comment=keep
line_space_after_do_statement=keep
line_space_after_expression_statement=keep
line_space_after_for_statement=keep
line_space_after_function_statement=keep
line_space_after_if_statement=keep
line_space_after_local_or_assign_statement=keep
line_space_after_repeat_statement=keep
line_space_after_while_statement=keep
line_space_around_block=keep
max_line_length=90
never_indent_before_if_condition=true
never_indent_comment_on_if_branch=true
quote_style=double
remove_call_expression_list_finish_comma=true
space_after_comma=true
space_after_comma_in_for_statement=true
space_around_concat_operator=false
space_around_math_operator=true
space_around_table_append_operator=false
space_around_table_field_list=true
space_before_attribute=true
space_before_closure_open_parenthesis=false
space_before_function_call_open_parenthesis=false
space_before_function_call_single_arg=always
space_before_function_open_parenthesis=false
space_before_inline_comment=1
space_before_open_square_bracket=false
space_inside_function_call_parentheses=false
space_inside_function_param_list_parentheses=false
space_inside_square_brackets=false
table_separator_style=comma
trailing_table_separator=smart
```

**Comment by CppCXY** [comment]
I determined through binary search that the issue is with the option `end_statement_with_semicolon=never`. This feature was not implemented by me, so it's possible that the testing was not thorough enough.

**Comment by CppCXY** [comment]
@AndreaWalchshoferSCCH Dd you have time to fix this issue?

**Comment by CppCXY** [comment]
I suggest that you delete that line of configuration for now.
by the way, due to the extensive support for different options in the tool, formatting may not happen all at once in order to balance the varying values of these options. Additionally, my formatting behavior may vary based on the current layout. I have also observed that clang-format behaves similarly and does not format everything in one go to reach the final target.

**Comment by ddickstein** [comment]
Ok, thanks for letting me know and for the fast investigation! Do you know if there's a way to enable a single-line anonymous function as I had it in the original example? It's kind of nice for very short functions.

**Comment by CppCXY** [comment]
the default behavior of this tool is to respect the current layout, which means that when it detects a single-line layout, it will keep it as a single line unless it exceeds the `max_line_width` limit.

**Comment by ddickstein** [comment]
Ah, sorry I misunderstood at first. Great, the default behavior here is what I want.

**Comment by AndreaWalchshoferSCCH** [comment]
I can look into the reason why the formatting "evolves" on multiple passes, but the general behavior was expected to be like that. 
See the readme for `end_statement_with_semicolon = never`: "no statement should end with semicolon, all semicolons at the end of statements will be removed, **lines with multiple statements will be separated into multiple lines**"

But as for keeping anonymous functions on a single line - the most appropriate configuration value would be `same_line`. But that would keep semicolons like in 
```local opts = { on_exit = function(); job = nil end }```

In some cases, semantics change if you remove semicolons (what `never` does), so I decided to stay on a safer side and insert linebreaks when I remove semicolons in the middle of a line.
It wouldn't be a lot of effort to implement another configuration value that does remove all semicolons, but not add linebreaks. I'm not sure about a good naming for that, though.

**Comment by CppCXY** [comment]
> I can look into the reason why the formatting "evolves" on multiple passes, but the general behavior was expected to be like that. See the readme for `end_statement_with_semicolon = never`: "no statement should end with semicolon, all semicolons at the end of statements will be removed, **lines with multiple statements will be separated into multiple lines**"
> 
> But as for keeping anonymous functions on a single line - the most appropriate configuration value would be `same_line`. But that would keep semicolons like in `local opts = { on_exit = function(); job = nil end }`
> 
> In some cases, semantics change if you remove semicolons (what `never` does), so I decided to stay on a safer side and insert linebreaks when I remove semicolons in the middle of a line. It wouldn't be a lot of effort to implement another configuration value that does remove all semicolons, but not add linebreaks. I'm not sure about a good naming for that, though.

I think the 'never' option should just delete the semicolon. If an option has too many functions and cannot be reflected in the name, this will cause a difference in understanding. I don't want an option to violate common knowledge. Of course, this It's a function you implement. I won't change it too much myself, but if there are too many problem reports about this option, I may choose to modify it.
