### ISSUE TITLE
连续行末注释对齐的设置参数

### ISSUE THREAD

**Issue by MrZ626** [CppCXY/EmmyLuaCodeStyle#142]
```lua
a=1 -- 1
b=12345 -- 12345
```
会被格式化成
```lua
a=1     -- 1
b=12345 -- 12345
```
感觉注释一般不太需要这个
顺便“连续行”感觉起码3连才算吧，所以对连续行进行的不同动作每个都可以支持一下设置多少才算连续的设置？
文档里边没找到，看起来是完全没有相关

**Comment by CppCXY** [comment]
感觉不需要可以关掉, 不是所有选项都在文档里面, 连续行不是触发的条件只是延续的条件.
