### ISSUE TITLE
Methods don't respect indent_size

### ISSUE THREAD

**Issue by gepbird** [CppCXY/EmmyLuaCodeStyle#143]
I have indent_size set to 2 spaces, but when splitting chained methods into multiple lines, they will get the default 4 space indentation.

Formatted:
```lua
foo = {
  bar = 'baz', -- 2 space indent works for almost everything
}

foo:bar()
    :baz() -- except for method calls on a new line

foo
    :bar()
    :baz()
```

Expected:
```lua
foo = {
  bar = 'baz',
}

foo:bar()
  :baz()

foo
  :bar()
  :baz()
```

**Comment by CppCXY** [comment]
it is `continuation_indent = 2`

**Comment by CppCXY** [comment]
Other options related to chain calls include
# option none / always / only_call_stmt
align_chain_expr = none

It is possible that I do not have enough documentation to describe many of the newly added options, so it is normal for you not to know about them either.

**Comment by gepbird** [comment]
Thanks for you quick response, works like a charm!
