### ISSUE TITLE
Option to apply 'max_line_length' to comments

### ISSUE THREAD

**Issue by ArmoredPony** [CppCXY/EmmyLuaCodeStyle#147]
'max_line_length' option decides when to chopdown the code. Could you please add an option that would wrap comments that exceed this line limit as well? As I see it, this feature should wrap only those lines that don't have any code before a comment.

I apologize if this feature is already present in formatter and I was unable to find it.

**Comment by CppCXY** [comment]
why need this feature

**Comment by ArmoredPony** [comment]
I document my code heavily. Lua is a very ambiguous language with its type system and replacing non-supplied arguments with nils so documentation is a must-have. Sometimes I need to change something in the docs which makes certain strings longer. And it's a pain to manually copy-paste words from one string to another to make them fit length of 80 symbols. Sometimes a string gets shorter after a change which allows to put on it a word or two from a string below that. So the string below gets shorter and so on.

I'd be glad if the formatter would trim long comment lines for me

**Comment by CppCXY** [comment]
This is a difficult task as it involves what is known as boundary issues. Comments have much richer formatting than code, and they often contain descriptions composed of peculiar encodings. Some characters that appear to be two characters long are actually three characters long. Additionally, the composition of words in different languages can be quite peculiar. It is challenging for me to interrupt the process at any point. On the other hand, emmyluadoc is generated from comments, and currently, it does not support line breaks. This feature would disrupt the way emmylua parses comments.

**Comment by ArmoredPony** [comment]
Understandable. Nevermind then
