### ISSUE TITLE
Add table align support for UTF8 Latin Extended-A

### ISSUE THREAD

**Issue by gepbird** [CppCXY/EmmyLuaCodeStyle#151]
`align_array_table` doesn't work for the following example:
```lua
with_latin_extended_a = {
  { 'aaaa', nil },
  { 'ő', nil }, -- U+0151
  { 'ű', nil }, -- U+0171
}
```

This is a continuation of #146, sorry for not testing all the test cases that time and opening a separate issue now. However I believe it isn't too much effort to add, compared to the last issue. As always thank you for your quick and hard work!

**Comment by CppCXY** [comment]
do you want me extend to Latin B characters?

**Comment by gepbird** [comment]
Personally I don't (or very rarely in LaTeX, not in lua) use any characters from Extended-B, but I can image it being useful for someone else.

**Comment by CppCXY** [comment]
I have update the range to U+024F, you can compile by yourself, Sumneko Lua will not be updated for six months.
And I am also writing a new language server myself, which may not be updated so diligently

**Comment by gepbird** [comment]
I've updated your repo in my fork of lua-language-server, built it and it works. Thanks!
