### ISSUE TITLE
怎么配置EmmyLuaCodeStyle在Idea中？

### ISSUE THREAD

**Issue by TikLiu** [CppCXY/EmmyLuaCodeStyle#153]
怎么配置EmmyLuaCodeStyle在Idea中？以及在Idea中快速格式化的快捷键是什么？

**Comment by CppCXY** [comment]
在项目跟目录创建.editorconfig, 他的配置你可以看本项目的lua.template.editorconfig, 格式化快捷键是idea标准快捷键ctrl alt l
