### ISSUE TITLE
Disable comment alignment/comment formatting

### ISSUE THREAD

**Issue by ImSkully** [CppCXY/EmmyLuaCodeStyle#154]
Is it possible to completely disable formatting of comments? At the moment, the following code:
```lua
local key = "value" 		-- My comment
local otherkey = "value"	-- My second comment
```

Gets converted to:
```lua
local key = "value" -- My comment
local otherkey = "value" -- My second comment
```

Setting `align_continuous_inline_comment` to `false` resolves this, but then `space_before_inline_comment` will immediately also format this to the configured number of spaces. As far as I can see, there isn't a way to disable both `align_continuous_inline_comment` and `space_before_inline_comment` so I can freely indent and align comments myself.

I only want to use formatting for code itself and not comments since there are different styles of commenting that combine both variations of what you see above within the same project and the current formatting configuration is limited since it doesn't allow for this.

A good example of this is having alignment for all comments enabled, except for when alignment would exceed the `max_line_length` in which case it would be preferred to space comments using `space_before_inline_comment` instead:

```diff
// Assume this line is the configured max length => -----------------------------------------------------------------|

// ✅ This should align comments
-- local key = "value" -- My comment
-- local otherkey = "value" -- My second comment
++ local key = "value"      -- My comment
++ local otherkey = "value" -- My second comment

// ❌ This should not align comments since it would exceed max length:
-- local ANOTHER_REALLY_LONG_KEY_NAME = "ANOTHER_REALLY_LONG_VARIABLE_VALUE" -- My slightly longer comment
-- local A_REALLY_LONG_KEY_NAME, A_SECOND_INLINE_LONG_VARIABLE = "A_REALLY_LONG_VARIABLE_VALUE", false -- My comment
++ local ANOTHER_REALLY_LONG_KEY_NAME = "ANOTHER_REALLY_LONG_VARIABLE_VALUE"                           -- My slightly longer comment
++ local A_REALLY_LONG_KEY_NAME, A_SECOND_INLINE_LONG_VARIABLE = "A_REALLY_LONG_VARIABLE_VALUE", false -- My comment
```

If you do incorporate alignment to respect the `max_line_length` value, it would be ideal to have a separate `max_comment_line_length` so comments can be adjusted separately.

**Comment by CppCXY** [comment]
Is there a formatter for other languages that supports this?

**Comment by ImSkully** [comment]
I'm not aware of any other formatters that provide `align_continuous_inline_comment` functionality. There was a request for Prettier to implement this which was rejected: https://github.com/prettier/prettier/issues/10068

Considering this formatter provides this functionality, the `align_continuous_inline_comment` should respect `max_line_length` or a new `max_comment_line_length` value and avoid formatting if it would result in the length being exceeded.

**Comment by CppCXY** [comment]
The implementation of this feature itself is indeed more difficult for other formatters. Since you don't want inline comments to be formatted, offering an option to preserve the absolute position of inline comments might be a better choice. It's too late now, I'll look into it tomorrow.

**Comment by CppCXY** [comment]
I have implemented this feature. After future updates, you can set `space_before_inline_comment = keep` to keep the relative distance of inline comments.

**Comment by ImSkully** [comment]
Thank you for the quick implementation, considering I'm making use of EmmyLua through the sumneko/Lua VSCode extension I assume they will need to update the shipped version of EmmyLua before this change becomes available.

**Comment by CppCXY** [comment]
you can try my own plugin https://marketplace.visualstudio.com/items?itemName=CppCXY.emmylua-codestyle

**Comment by ImSkully** [comment]
Thanks for the info, though I require the additional logic from the Lua VSCode extension as well alongside this plugin - what is the process for getting them to update it on their end? I'm have to submit an issue/PR on their repository if they'll accept it though let me know if you're aware of how to go about this.

**Comment by CppCXY** [comment]
sumneko has been updated with my updates, usually he merges it after I submit the PR, but he doesn't always release the updates in time, maybe once a month to two months.
