### ISSUE TITLE
EditorConfig property quote_style is probably misspelled

### ISSUE THREAD

**Issue by marciomazza** [CppCXY/EmmyLuaCodeStyle#155]
On `lua.template.editorconfig` we see the line:
```
quote_style = none
```
but the EditorConfig actual property for that is called `quote_type`
(see https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties)

**Comment by CppCXY** [comment]
When I implemented this feature, I looked at the editorconfig website, and there was no description of qoute_type. Maybe I didn't find it. And editorconfig itself doesn't implement this feature, so it makes sense for me to name it that way. But now that you mention it, I can accept the option of compatibility.
