### ISSUE TITLE
Separate Continuation Indent for Block Statements

### ISSUE THREAD

**Issue by firas-assaad** [CppCXY/EmmyLuaCodeStyle#156]
Thanks for developing this formatter!

I use a convention of 4 spaces for continued lines for regular statements, but 8 spaces for lines after the start of a block (e.g. `if` statement, function declaration, loops) to clearly distinguish the block container from the statements inside it:

```lua

local regular_statement = 'hello '
    .. 'world

function func(a, b,
        c, d)
    print('hi')
end

if a > 2
        and b == 5
        and c = 3
    return 1
end
```

As far as I can tell `continuation_indent` applies to both cases. Is there a way to have a different indent before statements inside a block?

**Comment by CppCXY** [comment]
I'm sick, I'll implement it in a few days.

**Comment by firas-assaad** [comment]
> I'm sick, I'll implement it in a few days.

It's not really urgent, but thanks for taking the time to reply. I hope you get well soon!

**Comment by CppCXY** [comment]
after update you can set `continuation_indent.before_block = 8`
