### ISSUE TITLE
Preserve Spaces Before Single-Argument Function Call

### ISSUE THREAD

**Issue by firas-assaad** [CppCXY/EmmyLuaCodeStyle#157]
Usually I like to have a space before a function call with a single string or table argument, but I have a few special functions where I don't want to have spaces. For example:

```lua
function L(lambda_string)
    -- Turns the lambda string into a function
end

local f = L'x, y => x > y' -- the same as: local f = function(x, y) return x > y end
```

I realize this is a very specific use case, so I was wondering if there's a way to simply turn off the `space_before_function_call_single_arg` setting. Something like "keep" or "preserve".

Edit: ideally with different settings for tables and strings. I still want to always have a space before tables.

**Comment by CppCXY** [comment]
set `space_before_function_call_single_arg=only_table`

**Comment by CppCXY** [comment]
see https://github.com/CppCXY/EmmyLuaCodeStyle/blob/ebcd76a256ad5b36b9645ae89ca17360bafbdc2a/lua.template.editorconfig#L49C1-L52C47

**Comment by CppCXY** [comment]
you can set `space_before_function_call_single_arg.string = keep`

**Comment by firas-assaad** [comment]
Thank you so much for adding this option (and the one for continuation too). I'll wait for the release.
