### ISSUE TITLE
space_around_math_operator and exponentiation operator

### ISSUE THREAD

**Issue by emmericp** [CppCXY/EmmyLuaCodeStyle#161]
`space_around_math_operator` currently enforces spaces around all math operators, but I think it is a somewhat common style to skip spaces around the exponentiation operator to express its strong binding.

For example, I would like to format code like this:

```
foo = x^32 + x^26 + x^23
```

**Comment by CppCXY** [comment]
maybe we need a option `space_around_math_operator.exp = false`

**Comment by CppCXY** [comment]
the new option is "space_around_math_operator.exponent = false"
