### ISSUE TITLE
Disable codes format in a block

### ISSUE THREAD

**Issue by godotc** [CppCXY/EmmyLuaCodeStyle#164]
If I want format a document, except some rows of codes in a block/region. Any configuration for it?

Like the clangd：
```cpp
// clang-format on
...
Codes here will be ignore by the formatter
...
// clang-format off
```

**Comment by CppCXY** [comment]
`---@format disable` will disable the formatting under it within the same block.
`---@format disable-next` will disable the formatting under it, but only one syntax element
but I donot implement `---@format on`

**Comment by godotc** [comment]
Thanks! Helps a lot:)
