### ISSUE TITLE
可以把文件名变黄色加一个功能开关吗？

### ISSUE THREAD

**Issue by YaoYilin** [CppCXY/EmmyLuaCodeStyle#165]
打开项目里其他人的代码，文件名变色体验不是很好，能否加个开关，不要改变 tabs 的字体颜色？

**Comment by CppCXY** [comment]
文件名是否为黄色是由编辑器本身决定的, 为黄色的来源是插件诊断出代码有不正确的排版, 给予的警告. 除非你不要代码格式检查不然应该是无法关掉黄色文件名

**Comment by YaoYilin** [comment]
好的~感谢~~~
