### ISSUE TITLE
align_continuous_inline_comment line space option

### ISSUE THREAD

**Issue by damil42** [CppCXY/EmmyLuaCodeStyle#166]
It would be great if I can configure the max empty lines for `align_continuous_inline_comment `.  

## Actual

```lua
blahblahblahblahblah = 1     -- one
blahblahblah = 2             -- two
blahblahblahblahblahblah = 3 -- three

blah = 4                     -- four
blahblah = 5                 -- five
```

## Expected

```lua
blahblahblahblahblah = 1     -- one
blahblahblah = 2             -- two
blahblahblahblahblahblah = 3 -- three

blah = 4     -- four
blahblah = 5 -- five
```

But this currently only works if 2 empty lines are between that blocks.  I want to set this to only 1 empty line. Is this already possible?

Otherwise I need to insert 2 empty lines in code, what I want to avoid.

```lua
blahblahblahblahblah = 1     -- one
blahblahblah = 2             -- two
blahblahblahblahblahblah = 3 -- three


blah = 4     -- four
blahblah = 5 -- five
```

**Comment by CppCXY** [comment]
because dc2a0dd44797838c74308dfd636348fcd7d1eccc
