### ISSUE TITLE
Option to insert one space in comment between -- and text

### ISSUE THREAD

**Issue by damil42** [CppCXY/EmmyLuaCodeStyle#167]
Without that option:

```lua
--hello
test --hello
--    another
test --        lol
```

with that option:

```lua
-- hello
test -- hello
-- another
test -- lol
```

That option ensures exact one space btween `--` and the text.

**Comment by CppCXY** [comment]
There are problems with this option, such as
---```lua
---function f()
---    local t = 123
---end
---```

this option will remove the indentation of the doc format

**Comment by CppCXY** [comment]
the current language server plugin does not parse comments according to Markdown syntax, but instead parses them based on EmmyLua Doc. when displaying comments, it concatenates each line of ordinary comments with \n and places them into the MarkdownContent structure specified by the Language Server Protocol (LSP). therefore, the language server itself does not know where the so-called code block starts and ends.

the only thing I can do is to add a space to the ones that don't have a space, and leave the ones that do have a space.

**Comment by CppCXY** [comment]
I've implemented the features you asked for, so if you want to experience it right away you can just install it.
https://marketplace.visualstudio.com/items?itemName=CppCXY.emmylua-codestyle
If you want to wait for sumneko lua updates, it's going to be a long time.
