### ISSUE TITLE
诊断结果中添加类别字段

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#18]
我可以在上层根据类别来进行消息本地化，或是实现单独禁用某个诊断等功能

**Comment by CppCXY** [comment]
内部其实有翻译系统，只是没有引入到lib中去，由于诊断中很大部分是拼接的字符串，所以最好使用我提供的翻译系统。
诊断类型待分离完成后再说。

**Comment by sumneko** [comment]
可以把详细的信息都返回回来，例如：

```lua
{
    type = 'MISS_SYMBOL',
    info = {
        symbol = 'end',
    },
    message = 'miss symbol `end`',
}
```

我可以直接使用 `message` ，也可以自己格式化为 `缺少符号 "end"`
