### ISSUE TITLE
默认会在倒数第二个字符上显示背景色

### ISSUE THREAD

**Issue by imcloud** [CppCXY/EmmyLuaCodeStyle#181]
IntelliJ IDEA 2024.1.4 (Community Edition)

插件版本：1.5.0.25-IDEA223

问题：

在未进行任何选择操作的情况下，倒数第二个字显示选择状态的背景色

![image](https://github.com/user-attachments/assets/2ef59e80-720b-4f80-9c4f-e75bb9f936da)

如图最后一行‘s’看样子是选中状态，实际上我没有，光标在第六行正准备打字输入

禁用插件后状态会恢复正常

**Comment by CppCXY** [comment]
这是插件的诊断, 说你不是以新行结束,出于一些原因在idea上无法正常的标记在最末尾的位置

**Comment by imcloud** [comment]
原来如此，按个回车果然没了
