### ISSUE TITLE
Ubuntu nvim format 会在行尾出现^M

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#20]
格式化后每行末尾都会出现^M（windows的换行符）

原issue：https://github.com/sumneko/vscode-lua/issues/55

**Comment by CppCXY** [comment]
不是有选项
```
end_of_line = lf
```

**Comment by sumneko** [comment]
非Windows下难道不是强制 `lf` ?

**Comment by CppCXY** [comment]
当然不是，一份代码，在不同平台编辑，结果行尾都不一致并且无法被控制，可能不太合理

**Comment by CppCXY** [comment]
我可以认为在非windows平台，在不配置的情况下可以默认lf

**Comment by sumneko** [comment]
换行符一般都是跟本地环境绑定的吧，或者你搞个默认值 `auto`

**Comment by CppCXY** [comment]
暂时是非windows平台默认值 lf,如果配置了就按配置的走。auto配置后面再加
