### ISSUE TITLE
Default editorconfig

### ISSUE THREAD

**Issue by szaffarano** [CppCXY/EmmyLuaCodeStyle#21]
Hi, I use neovim and the sumneko LSP server, and I started using the new [code formatting feature](https://github.com/sumneko/lua-language-server/commit/0f63b39275be9c5c3eb3bca27f5bd660cdc0ae26). BTW, thanks!!! great job :)
Even though it works great if I have a `.editorconfig` file in my project root, I wondered if it's possible to set a default configuration, so I don't need to set it in every project, but only when I want to change something. 
Thanks!

**Comment by CppCXY** [comment]
I would consider this feature

**Comment by CppCXY** [comment]
This feature has been merged, and after release you need to set Lua.format.defaultConfig like:
```json
”Lua.format.defaultConfig“:{
   ”indent_style“:"space"
}
```
Maybe it is lua code, I don't know how you set it up

**Comment by sumneko** [comment]
Off topic, but I think indent should use `insertSpaces` of [formattingOptions](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions)

**Comment by CppCXY** [comment]
But 'indent_style' is the standard name provided by editorconfig.

**Comment by CppCXY** [comment]
And I think it is more recognizable

**Comment by sumneko** [comment]
Since LSP specifies that this field will be included in the formatted request, you should use the LSP field first.
You should only use the settings in `.editorconfig` if formatting is not requested via LSP.

**Comment by CppCXY** [comment]
new issue Please
