### ISSUE TITLE
Use `insertSpaces` in `formattingOptions` instead of `indent_style` in `.editorconfig`

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#22]
See https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions

Since LSP specifies that this field will be included in the formatted request, you should use the LSP field first.
You should only use the settings in `.editorconfig` if formatting is not requested via LSP.

**Comment by CppCXY** [comment]
1. vscode 平台，如果安装了editorconfig插件，那么编辑器的设置会被强行设置为editorconfig指定的属性
2. 如果没有安装该插件，按照普遍的习惯或者约定，如果插件支持editorconfig那么是editorconfig设置会覆盖编辑器设置
3. 对VisualStudio或者jbIDE当检测到editorconfig,会询问是否由editorconfig覆盖本地设置

也就是说对于支持editorconfig的插件普遍的认知是editorconfig优先。

**Comment by sumneko** [comment]
这个优先不是你来做的，是VSCode来做的。
也就是VSCode会修改他发给你的 `insertSpaces` 才对。

**Comment by CppCXY** [comment]
但是要考虑到vscode并没有直接支持editorconfig，默认情况下他是不认识的，所以就会形成认知偏差: 我明明editorconfig设置了tab但是为什么格式化还是space。

**Comment by sumneko** [comment]
其他客户端我不清楚，但是VSCode会清楚在右下角显示你当前的缩进规则，我觉得应该尊重这里的规则

**Comment by CppCXY** [comment]
那我就没有办法简单的将space写的切换成tab写的了

**Comment by sumneko** [comment]
![image](https://user-images.githubusercontent.com/5213431/154922799-31610959-498f-4212-8788-c66c9d0b6554.png)
自己点一下右下角的缩进规则就好了

**Comment by CppCXY** [comment]
关键是让设置形同虚设我认为不好，我可以认为在没有editorconfig的时候按编辑器配置做

**Comment by sumneko** [comment]
![image](https://user-images.githubusercontent.com/5213431/154923113-d31532e0-cc43-4e37-b535-cc40c8bd3cb1.png)
你可以参考一下其他格式化程序，比如 `prettier` 就是 editorconfig 的优先级是最低的

**Comment by CppCXY** [comment]
我可以实现这个，但是你最好让人们讨论一下

**Comment by CppCXY** [comment]
诊断是没有这个参数的，所以诊断对于indent_style的配置还和格式化不一样,这合理吗。

**Comment by CppCXY** [comment]
解决方案：代码诊断不再采用editorconfig。 代码诊断算法重写，由一个.lualint.json(模仿eslint)文件重新配置。

**Comment by FlashHit** [comment]
so that's why `insertSpaces` was broken. I wasted at least 20 minutes on this cuz I didn't know this was part of the lua extension.

**Comment by CppCXY** [comment]
将使用formatOptions的insertOptions和tabSize参数
