### ISSUE TITLE
关于括号嵌套的格式化有些问题

### ISSUE THREAD

**Issue by qiulaohu-cn** [CppCXY/EmmyLuaCodeStyle#24]
使用环境是cocoslua
应该是这样的
![image](https://user-images.githubusercontent.com/74034872/155451393-34c191e6-7c64-4308-ba84-23317751d95b.png)
使用格式化后的样式
![image](https://user-images.githubusercontent.com/74034872/155450936-cde2531f-1453-4062-90ee-52747cd28ea5.png)

**Comment by CppCXY** [comment]
这个bug出现在函数单参数的情况下

**Comment by CppCXY** [comment]
我下午会改好

**Comment by CppCXY** [comment]
bug已经修复等下次sumneko lua更新的时候就有效了。
现在你可以采用选项 `align_call_args = true` 缓解这个状况，
或者安装EmmyluaCodeStyle插件立即获得这次更新。
