### ISSUE TITLE
Code format not running.

### ISSUE THREAD

**Issue by michaelwestbrook** [CppCXY/EmmyLuaCodeStyle#29]
I get a 'formatter not installed' error when I try to format code. I have format enabled and I am trying to use the default .editorconfig in my root directory.

**Comment by michaelwestbrook** [comment]
oops, wrong place. sorry

**Comment by CppCXY** [comment]
The formatter can be enabled by adding the parameter --preview to the command line parameters.
For VSCode, add this parameter in the Lua.misc.parameters setting.
see https://github.com/sumneko/lua-language-server/issues/960
