### ISSUE TITLE
[Enhancement] comments on `elseif` statements

### ISSUE THREAD

**Issue by FlashHit** [CppCXY/EmmyLuaCodeStyle#30]
It would be nice if this could be improved to not do this:

![grafik](https://user-images.githubusercontent.com/56718716/158693693-31ced528-6650-4af1-86b1-060d74831127.png)

**Comment by CppCXY** [comment]
But how do I define which comments don't indent，
for example：
```lua
if a then
---0
local t  = 123
---1

---2
---3
elseif b c then
end
```
and only comments
```lua
if a then
--body
elseif d then
end
```

**Comment by FlashHit** [comment]
Idk if you can but I would suggest to let the comment where it is when it’s before an elseif. 

```lua
if a then

    --inside comment
elseif b then

--outside comment
elseif c then
    --something
end
```

**Comment by CppCXY** [comment]
I would consider this feature

**Comment by CppCXY** [comment]
If there is no meaningful statement block, the comment is all indented as a block, otherwise comments below the meaningful block are considered to belong to the comments of the elseif/else branch

**Comment by FlashHit** [comment]
> If there is no meaningful statement block, the comment is all indented as a block, otherwise comments below the meaningful block are considered to belong to the comments of the elseif/else branch

sounds good 👍

**Comment by CppCXY** [comment]
this feature has been implemented by option `if_branch_comments_after_block_no_indent = true`.
The next release, the feature will be available
