### ISSUE TITLE
Clear postemptive spaces on comments

### ISSUE THREAD

**Issue by FlashHit** [CppCXY/EmmyLuaCodeStyle#31]
before:
![grafik](https://user-images.githubusercontent.com/56718716/158816988-2ded20eb-4565-4007-bf5a-f243a6a4c388.png)
after:
![grafik](https://user-images.githubusercontent.com/56718716/158817027-43f973ed-9431-498b-bfdb-a1bbbe32e01b.png)

why doesn't the formatter clear all postemptive spaces? Seems like it ignores the comments

the lua extension has a function that would clear this as well:
![grafik](https://user-images.githubusercontent.com/56718716/158817329-5280db21-72b5-4e52-882f-ad9eca86cf35.png)

**Comment by CppCXY** [comment]
this feature has been implement, wait for next release
