### ISSUE TITLE
格式化选定内容/粘贴时格式化的问题

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#35]
```lua
TEST [[
---@class Class

---@param k Class
for <?k?> in pairs(t) do
end
]]
[[
parameter k: Class
]]
```

选中倒数第二行的 `parameter`，选择 `格式化选定内容` 后，会导致倒数第三行格式改变，变为：
```lua
TEST [[
---@class Class

---@param k Class
for <?k?> in pairs(t) do
end
]]
    [[
parameter k: Class
]]
```

**Comment by CppCXY** [comment]
对于范围格式化，这里需要明确的是被选中的范围有可能不具备完整的语法和正确的缩进，所以算法会扩选到最小的语法单元，对于被选中的行，实际上它是最小的格式化单元——字符串字面值常量的一部分，所以他会被扩选到字符串，然后就上下文分析他应该是连续调用语句的参数所以会补上缩进，算法本身不允许改变字符串内容所以不会改变字符串内的值。

**Comment by sumneko** [comment]
扩张范围合理，问题是我换过行后是不是不应该要缩进了。

**Comment by CppCXY** [comment]
那我可以认为是，连续的调用表达式，在首个参数主动换行时，不予缩进

**Comment by CppCXY** [comment]
我觉得应该是连续调用表达式链中无括号单参数，主动换行时可以不予缩进

**Comment by sumneko** [comment]
正常情况下应该是左括号吧，如果没有左括号再处理字面量字符串/表的省略形式

```lua
f()
(
    1,
    2,
)
```

```lua
f()
{
    x = 1,
    y = 2,
}
```

```lua
f()
[[
string content
]]
```

**Comment by sumneko** [comment]
这么一看的话，就是换行后直接把它当做独立的语句看待就好了

**Comment by CppCXY** [comment]
晚上再看
