### ISSUE TITLE
`local x <close>` 格式化后会丢失空格

### ISSUE THREAD

**Issue by sumneko** [CppCXY/EmmyLuaCodeStyle#36]
会被格式化为 `local x<close>` 。
我觉得大部分的习惯（以及lua官方的测试代码中）都是保留空格的，因此默认保留空格比较好。

**Comment by CppCXY** [comment]
`keep_one_space_between_namedef_and_attribute = false` 该选项默认是false，改为true就好了

**Comment by sumneko** [comment]
直接默认改true吧

**Comment by CppCXY** [comment]
那好吧
