### ISSUE TITLE
How to disable max_line_length check

### ISSUE THREAD

**Issue by rockyzhang24** [CppCXY/EmmyLuaCodeStyle#37]
Is it possible to disable the check of max_line_length? Thank you.

**Comment by CppCXY** [comment]
set `max_line_length=999`

**Comment by rockyzhang24** [comment]
That’s exactly what I was thinking. But it is not ideal. Because it may have all the contents in one line in some cases. It’s better to have a value like `-1` representing totally disabled checking. 

Thanks a lot.

**Comment by CppCXY** [comment]
for the current version `max_line_length` does not affect formatting

**Comment by CppCXY** [comment]
There will be a separate linter configuration in future versions, but for now I'm mainly updating `Emmylua`

**Comment by rockyzhang24** [comment]
You get me wrong. I'm not talking about formatting. I mean in some cases, maybe some file has all content in one line. When we browser such a file, setting it to `999` still makes the diagnostic info shown. That's annoying. What I am expecting is that when we open such a file, no max_line_lengh checking there. Thank you.

**Comment by CppCXY** [comment]
allow set `max_line_length=unset` ,the line width is no longer checked.
next release get this update.

**Comment by CppCXY** [comment]
allow set `max_line_length=unset` ,the line width is no longer checked. (In fact it is set to INT_MAX)
next release get this update.
