### ISSUE TITLE
Count of spaces before inline comment

### ISSUE THREAD

**Issue by rockyzhang24** [CppCXY/EmmyLuaCodeStyle#39]
Currently the count of spaces before inline comment is 1. Is it possible to set it to a value we want? Thanks a lot.

**Comment by CppCXY** [comment]
This need a lot of work on comment，because inline comments can be inserted into almost any part of any statement。

**Comment by rockyzhang24** [comment]
Make sense. Definitely hard to implement. Hope this customization can be added in the future. Thank you.

**Comment by CppCXY** [comment]
maybe you just hope
```lua
local b = ccc<custom space>--inline
pcall(f,1,2,3)<custom space>--inline
```

**Comment by rockyzhang24** [comment]
Yep. 👍

**Comment by CppCXY** [comment]
for me 
````lua
local --[[aaaa]]
a = 123
````
Just to make sure the syntax is correct

**Comment by rockyzhang24** [comment]
Yes. I just want to set it to `2` that is more common than `1`. The Lua Style Guide in lua-users wiki uses 2 spaces before the inline comment as well.

**Comment by CppCXY** [comment]
This feature has been implemented, waiting for the next release

**Comment by rockyzhang24** [comment]
Nice! Thank you very much.

**Comment by rockyzhang24** [comment]
Hi @CppCXY It seems this option `statement_inline_comment_space` doesn't work in Neovim. The lua-language-server is the latest version, 3.2.3. 

I set it in this way:

```lua
nvim_lsp.sumneko_lua.setup {
  
  -- Other settings

  settings = {
    Lua = {
      
      -- Other settings

      format = {
        enable = true,
        defaultConfig = {
          indent_style = "space",
          indent_size = "2",
          max_line_length = "unset",
          statement_inline_comment_space = "2",  -- DOES NOT WORK
          -- quote_style = "double",
        },
      },
    },
  },
}
```

I tried both `statement_inline_comment_space = 2` and `statement_inline_comment_space = "2"`, and neither works. Other options I set in the snippet above such as `indent_style`  and `indent_size` work well. 

Thank you.

**Comment by CppCXY** [comment]
I try it in vscode, it work well with .editorconfig. but fail with defaultConfig

**Comment by CppCXY** [comment]
I know, If there is an editorconfig, only the settings in the editorconfig will be used

**Comment by rockyzhang24** [comment]
> I know, If there is an editorconfig, only the settings in the editorconfig will be used

I don't use .editorconfig and instead I just set `statement_inline_comment_space = 2` in Neovim `lsp-config` as I attached above. However, other options like `indent_size` works well without using .editorconfig as well, and just `statement_inline_comment_space` has no effect, so I believe it is a bug. 

Thanks a lot.

**Comment by CppCXY** [comment]
I am using vscode set this option, it works well. (3.2.3)
In fact the indent_style and indent_size options cannot be set.
Indentation only depends on the editor's settings for the current file

**Comment by CppCXY** [comment]
I'm not a neovim user, I'll learn about neovim later and look at this question

**Comment by rockyzhang24** [comment]
You said you fail to set it as well in defaultConfig for vscode, right? 
Also, for option quote_style, it works as well on my side if I only set it in defaultConfig.

**Comment by CppCXY** [comment]
At the time I had the .editorconfig file, I deleted it later. defaultconfig work well

**Comment by rockyzhang24** [comment]
I just uninstall `lua-language-server` and re-install it, and now setting `statement_inline_comment_space` in `defaultConfig` works. That's interesting. I will close this.
