### ISSUE TITLE
Region Folding indent

### ISSUE THREAD

**Issue by Sedas25** [CppCXY/EmmyLuaCodeStyle#42]
Befor Formating
![image](https://user-images.githubusercontent.com/35778952/166892965-a2213a2c-807f-4e38-b2c2-e072b4d8af45.png)
After:
![image](https://user-images.githubusercontent.com/35778952/166893023-487f2a1f-a4c7-4cd2-8109-7e69dc3198e2.png)

Befor is correct

**Comment by CppCXY** [comment]
If you use a plugin that supports emmylua doc, then `---#region` is not a standard folding annotation. `---region` is a folding annotation.

folding annotations usually do not have an indentation strategy, which can refer to C# or C language preprocessing, so it is unreasonable to have indentation in folded code blocks

**Comment by Sedas25** [comment]
i use the lua-language-server from sumneko
[folding.lua](https://github.com/sumneko/lua-language-server/blob/5d5a79fd52c2898bb3e238e750347d8ed9f4da6a/script/core/folding.lua#L99)
it allows both variants.

the problem is with no indentation VsCode show me no Folding

**Comment by CppCXY** [comment]
Because of the particularity of comments, if the code block inside the block fold is to be indented, then I can write it like this
```lua
if a then
---region
     local t = 13
end
---endregion
```
after formatting:
```lua
if a then
---region
         local t = 13
    end
---endregion
```

**Comment by CppCXY** [comment]
So how do I decide when to give such an indent

**Comment by Sedas25** [comment]
ok i understand the problem.
thank you for the quick answer
