### ISSUE TITLE
[Feature Request] Remove last comma for parameters and argumens

### ISSUE THREAD

**Issue by kevinhwang91** [CppCXY/EmmyLuaCodeStyle#43]
```lua
function foo(a1, ) end

foo(1,)
```
become 
```lua
function foo(a1) end

foo(1)
```

This behavior is like `gofmt`.

**Comment by CppCXY** [comment]
This is a syntax error for lua. Is there a good reason to format the wrong syntax

**Comment by kevinhwang91** [comment]
It's convenient to expand snippets for function.

If a snippet is expanded with two parameters and the last is optional, I can remove the last parameter with one keystroke (I have remapped the key) and jump the function body easily. 

Without this feature, I must remove the last parameter and type two keystrokes to remove space and last comma, and I can't jump the function body in the next jump in coc.nvim, look like the placeholder is broken in the session.

**Comment by CppCXY** [comment]
need some time for think about formatable errors

**Comment by CppCXY** [comment]
this feature has been implement, wait for next release

**Comment by kevinhwang91** [comment]
I build the updated code myself.
`CodeFormat check -f foo.lua` output `foo.lua(1:15 to 1:18): here need keep 0 space`, But `CodeFormat format -f foo.lua` output:
```lua
function foo(a1,) end

foo(1,)
```

**Comment by kevinhwang91** [comment]
Thanks, it works now.
