### ISSUE TITLE
"max_line_length": "120"，超出每行最大字符数时，部分情况下格式化后的折行会很离谱

### ISSUE THREAD

**Issue by Richard-Cat** [CppCXY/EmmyLuaCodeStyle#47]
格式化前：![image](https://user-images.githubusercontent.com/73878334/173059705-880db0b9-3ced-46fe-b940-82d48fc0ebd2.png)
格式化后：
第一次格式化：![image](https://user-images.githubusercontent.com/73878334/173059800-915d9228-6042-4e87-b473-3afd3084d845.png)
第二次格式化：![image](https://user-images.githubusercontent.com/73878334/173059849-75a2116c-3e92-4321-9a43-6679510cdb46.png)

**Comment by Richard-Cat** [comment]
"align_call_args": "true"，这个字段设置为true，即可出现上述问题

**Comment by CppCXY** [comment]
折行这个问题，是这样的。强如jetbrain他家的ide产品中的代码格式化依然会存在不合理折行。而我整个算法是保持原状算法，所以在二次格式化的时候我并不会把分行表示的参数列表重新合并在一行。
通常因为代码超长而折行的格式化如果不能满意，就ctrl z之后手动换一下行再格式化就行了

**Comment by Richard-Cat** [comment]
我现在把字段值改为1000了（"max_line_length": "1000"），以此来关闭折行。建议默认关闭折行，以免造成奇怪的代码格式。
另外，我正在使用的另外一款格式化插件LuaFormatter，个人觉得其在折行方面有独到之处（https://github.com/Koihik/LuaFormatter）

**Comment by CppCXY** [comment]
折行这个问题是因为我内置规则过于复杂，一开始没有考虑折行，是后面因为issue强行加的，这本来也不是我想要的。
你整个issue提出的问题在我首次做出来这个功能的时候就已经测出来了，但是我觉得这种情况还是很少见的所以一开始也没有管他。
折行这里比较理想的参考目标是reshaper的格式化方式或者clangformat，其他的就没什么参考价值。
目前手上事情也比较多，上班摸鱼的时候再来考虑折行的事情

**Comment by CppCXY** [comment]
这个问题已经修复
