### ISSUE TITLE
Disable formatting temporarily

### ISSUE THREAD

**Issue by Merhoc** [CppCXY/EmmyLuaCodeStyle#50]
Thanks a lot for your great work! I really like the formatter and use it frequently. I have a question regarding the functionalities:
Is there a possibility to disable formatting just like the [EmmyLua-Annotation diagnostic](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#diagnostic)?
Especially when it comes to automatic line breaks, such a thing would be really useful at certain points.

**Comment by CppCXY** [comment]
Thank you for liking my work, in fact the tool contains code style checking, code formatting and code spelling check. it is not just a formatter. 
It's a good idea to disable formatting with comments. but it need a lot of work, please wait patiently.

**Comment by CppCXY** [comment]
feature complete.
support disable format by
`---@format disable-next` or `---@format disable`
