### ISSUE TITLE
多行字符串不对齐，看起来很难受

### ISSUE THREAD

**Issue by sanpoo** [CppCXY/EmmyLuaCodeStyle#51]
```
local sql = fmt("select a, b, c " ..
    "from table " ..
    "where a > 10 and b < 10")
```
期待的格式：

```
local sql = fmt("select a, b, c " ..
                "from table " ..
                "where a > 10 and b < 10")
```

**Comment by CppCXY** [comment]
调用表达式中单参数跨行的格式化被特意调整为不对齐，虽然这个原则有问题，但是如果需要改的话，需要一个更好的原则。

**Comment by CppCXY** [comment]
周末再改。

**Comment by sanpoo** [comment]
羞答答的问一句，这个有进展吗

**Comment by CppCXY** [comment]
我要维护很多插件（最近新开发的是emmylua-unity），然后他就被搁置了。
而且我最近工作也比较忙，周四的时候我看一下吧。
如果有能力，你可以看一下代码，把luaFormatter.cpp中1248行到1261行的代码删掉就可以无视保护规则对齐函数调用的参数。

**Comment by CppCXY** [comment]
`align_call_args`这个选项的对齐原则变更为，如果调用表达式中不存在跨行的表表达式和闭包表达式则会对齐到第一个参数。
也就是允许像你那样写对齐到首个参数。

如果你是sumneko的用户则等待下一次他的更新，如果我emmyluacodestyle插件的用户，就等我晚上更新，或者从git action 下一个替换下可执行文件。

**Comment by sanpoo** [comment]
太棒了，感谢感谢🙏

**Comment by kevinhwang91** [comment]
```lua
local function create(f)
    return f()
end

local function eventOn(f)
    return f()
end

table.insert({}, create(function()
                 print('')
             end))
eventOn(function()
    print('')
end)
```
现在格式化变成这样了，eventOn不indent。希望给个选项吧，好丑。

**Comment by CppCXY** [comment]
> ```lua
> local function create(f)
>     return f()
> end
> 
> local function eventOn(f)
>     return f()
> end
> 
> table.insert({}, create(function()
>                  print('')
>              end))
> eventOn(function()
>     print('')
> end)
> ```
> 
> 现在格式化变成这样了，eventOn不indent。希望给个选项吧，好丑。

也就是希望在开启对齐选项的情况下，依然希望存在跨行表达式的不再对齐。还是希望对齐的原则能更具体一些

**Comment by kevinhwang91** [comment]
我个人更喜欢原来的风格。
before:
![image](https://user-images.githubusercontent.com/17562139/180122911-a2a0218b-5f41-4fb3-93fd-b7d888a0160f.png)

after:
![image](https://user-images.githubusercontent.com/17562139/180122989-58e34fa2-57ff-4330-9670-c0c47284f0cc.png)

**Comment by kevinhwang91** [comment]
> 如果不希望对齐的话就没必要开 align_call_args 这个选项, 还是希望在这个选项下有符合一般审美的例外规则

像层主这种情况有表达式赋值的，是好看的。
像我这种情况，无明显赋值不好看。

我喜欢align_call_args并希望两者都好看。

**Comment by CppCXY** [comment]
> > 如果不希望对齐的话就没必要开 align_call_args 这个选项, 还是希望在这个选项下有符合一般审美的例外规则
> 
> 像层主这种情况有表达式赋值的，是好看的。 像我这种情况，无明显赋值不好看。
> 
> 我喜欢align_call_args并希望两者都好看。

你得意思放弃在非赋值语句中函数对齐参数的行为

**Comment by CppCXY** [comment]
这个特性已经完成通过设置`align_call_args = only_after_more_indention_statement`就行了。

**Comment by kevinhwang91** [comment]
`cmake --build .`出错了， archlinux
`EmmyLuaCodeStyle/CodeFormatServer/src/Protocol/ProtocolBuffer.cpp:68:22: error: ‘copy_n’ is not a member of ‘std’; did you mean ‘copy’?`

**Comment by CppCXY** [comment]
> `cmake --build .`出错了， archlinux `EmmyLuaCodeStyle/CodeFormatServer/src/Protocol/ProtocolBuffer.cpp:68:22: error: ‘copy_n’ is not a member of ‘std’; did you mean ‘copy’?`

你所使用的archlinux-gcc 对C++标准支持力度不够，这是标准库的正常函数。
实际上你并不需要编译CodeFormatServer，所以创建cmake工程时需要定义cmake -DBuildCodeFormatServer=OFF

**Comment by kevinhwang91** [comment]
试了一下发现这个选项没什么用，会造成以下
```lua
local function new(o)

end

local super = new(setmetatable({}, {
    __index = function(t, i)
        return {}
    end
}))
```
变成
```lua
local function new(o)

end

local super = new(setmetatable({}, {
    __index = function(t, i)
        return {}
    end
                  }))
```
我还是
align_call_args = false 算了，感谢

**Comment by CppCXY** [comment]
> 试了一下发现这个选项没什么用，会造成以下
> 
> ```lua
> local function new(o)
> 
> end
> 
> local super = new(setmetatable({}, {
>     __index = function(t, i)
>         return {}
>     end
> }))
> ```
> 
> 变成
> 
> ```lua
> local function new(o)
> 
> end
> 
> local super = new(setmetatable({}, {
>     __index = function(t, i)
>         return {}
>     end
>                   }))
> ```
> 
> 我还是 align_call_args = false 算了，感谢

重新clone编译。
以前的效果归到选项：
`align_call_args = only_not_exist_cross_row_expression`

**Comment by kevinhwang91** [comment]
可以正常工作，谢谢
