### ISSUE TITLE
[enhancement] can we support the following functions?

### ISSUE THREAD

**Issue by achidipothu** [CppCXY/EmmyLuaCodeStyle#52]
Hello, Can we add support for the following functions? I use them for C/C++ on vscode. It will be pretty handy for me if they are available in Lua also.

- SpaceBeforeFunctionOpenParenthesis
- SpaceBeforeOpenSquareBracket
- SpaceBeforeLambdaOpenParenthesis
- SpaceWithinExpression
   
**SpaceBeforeFunctionOpenParenthesis**

Before Formatting:
```
function ff()
end
```
After Formatting:
```
function ff ()
end
```
**SpaceBeforeOpenSquareBracket**

Before Formatting:
```
details["names"] = "ashok"
```
After Formatting:
```
details ["names"] = "ashok"
```
**SpaceBeforeLambdaOpenParenthesis**

Before Formatting:
```
local details ={}
```
After Formatting:
```
local details = {}

```
**SpaceWithinExpression**

Before Formatting:
```
i?"true":"false";
i>0

```
After Formatting:
```
i ? "true" : "false";
i > 0
```

Thank You,
ashok.

**Comment by CppCXY** [comment]
If you want these features implemented, you can demonstrate how each option is formatted

**Comment by achidipothu** [comment]
sure, give me some time I will get back on this.

**Comment by achidipothu** [comment]
I updated the desired formatting in the description of the issue.

**Comment by CppCXY** [comment]
`SpaceBeforeLambdaOpenParenthesis` and `SpaceWithinExpression` is default action

**Comment by CppCXY** [comment]
only `SpaceBeforeFunctionOpenParenthesis` and `SpaceBeforeOpenSquareBracket` need support

**Comment by CppCXY** [comment]
option `SpaceBeforeFunctionOpenParenthesis` for lua, it is divided into function definition, function call, lambda definition. 
should I divide into three options?

**Comment by achidipothu** [comment]
> option `SpaceBeforeFunctionOpenParenthesis` for lua, it is divided into function definition, function call, lambda definition. should I divide into three options?

funtion call and defination need not be differentiated IMO.

**Comment by CppCXY** [comment]
feature has been completed
following option can use.
`space_before_function_open_parenthesis = true`
`space_before_open_square_bracket = true`

wait sumneko next update and release

**Comment by achidipothu** [comment]
:+1:

**Comment by CppCXY** [comment]
yes

**Comment by achidipothu** [comment]
:+1: 

I tried to use it in vain :( and here is how I set them up after I upgraded the version to 3.5.0. I also tried to refer to the [documentaion](https://github.com/CppCXY/EmmyLuaCodeStyle/tree/master/docs) but didnt find a mention of these two params there.

![image](https://user-images.githubusercontent.com/98626213/179863629-bc912cca-359b-45fa-9d2d-1c19e14f1f0b.png)

can you pls guide me on this configuration?

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/179879806-84298554-c2c3-4942-b8fc-b96af0a3ab77.png)
it work,if use .editorconfig.

**Comment by CppCXY** [comment]
maybe, in vscode setting, you can set "true" instead of true

**Comment by CppCXY** [comment]
this can be a misunderstanding. I will try to fix that

**Comment by CppCXY** [comment]
It's my mistake, when set default config, you need restart vscode.

**Comment by CppCXY** [comment]
if use .editorconfig. it can work?

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/180114217-57e91533-9be6-4b92-9560-da39aaad91ca.png)
I use your settings:
![image](https://user-images.githubusercontent.com/40318218/180114259-7d27bb98-d054-4747-a826-9d32980f541b.png)

**Comment by achidipothu** [comment]
> if use .editorconfig. it can work?

how do I use this? is it any difference from the settings that I am already using. Copy pasting them below for reference.

```
    "Lua.format.defaultConfig": {
        "align_call_args": "true",
        "space_before_function_open_parenthesis": "true",
        "space_before_open_square_bracket": "true"
    },
    "[lua]": {
        "editor.defaultFormatter": "sumneko.lua"
    },
```

**Comment by CppCXY** [comment]
see https://github.com/sumneko/lua-language-server/wiki/Code-Formatter

**Comment by CppCXY** [comment]
Is there any progress?

**Comment by achidipothu** [comment]
Doesnt work :( , Here is the full .editorconfig for your reference. FYI I am trying to format by using the `format selection` key.  Sorry for the delay, I was not feeling well this week.
```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[Makefile]
indent_style = tab
indent_size = 8

[*.py]
indent_style = space
indent_size = 4

"Lua.format.defaultConfig": {
    "align_call_args": "true",
    "space_before_function_open_parenthesis": "true",
    "space_before_open_square_bracket": "true"
},
"[lua]": {
    "editor.defaultFormatter": "sumneko.lua"
},

```

**Comment by CppCXY** [comment]
you can try my plugin https://marketplace.visualstudio.com/items?itemName=CppCXY.emmylua-codestyle
the .editorconfig copy from https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/lua.template.editorconfig

**Comment by achidipothu** [comment]
> you can try my plugin https://marketplace.visualstudio.com/items?itemName=CppCXY.emmylua-codestyle the .editorconfig copy from https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/lua.template.editorconfig

works good :+1: the formatting is also auto applied on a return key, just what I was looking for. Thank you very much. Its been pleasure working with you.

**Comment by ArmoredPony** [comment]
About `space_before_function_open_parenthesis`: would love to see this setting applied not only to round but to curly brackets as well. So `foo {}` is formatted to `foo{}` when this setting is `false`. By default, there is always a space between function name and curly brackets.

**Comment by CppCXY** [comment]
> About `space_before_function_open_parenthesis`: would love to see this setting applied not only to round but to curly brackets as well. So `foo {}` is formatted to `foo{}` when this setting is `false`. By default, there is always a space between function name and curly brackets.

new issue please
