### ISSUE TITLE
[Enhancement] Support of back ticks

### ISSUE THREAD

**Issue by AvaN0x** [CppCXY/EmmyLuaCodeStyle#53]
Hello, I would like to know if it would be possible to support back ticks.
They are used in fivem to replace the provided string as a Jenkins hash at compilation time.
https://forum.cfx.re/t/lua-support-for-compile-time-jenkins-hashes/600570?u=avan0x

While I'm not expecting them to have a special behavior when formatting, I would expect them to be ignored while formatting (or more support if wanted, I think ignoring them would be the easiest to implement?). At the moment, any file containing the back ticks like that is ignored by the formatter.

A simple example of use would be just:
```lua
local adderHash = `adder`
```
*(Having this single line will make the file not format)*

---

Setup used : VSCode with [sumneko.Lua](https://marketplace.visualstudio.com/items?itemName=sumneko.lua)

**Comment by CppCXY** [comment]
it is easy support.but wait for this weekend

**Comment by CppCXY** [comment]
support now, wait sumneko next release
