### ISSUE TITLE
[QUESTION] .editorconfig option to put table closing paranthesis to new line.

### ISSUE THREAD

**Issue by Real-Gecko** [CppCXY/EmmyLuaCodeStyle#54]
I have the following table:
```lua
Data = {
    howToBreakFormation = BreakImmediately,
    faceTargetHorizontal = 1,
    faceTargetVertical = 0,
    RandomActions =
    {
        {
            Type = PickNewTarget,
            Weighting = 1, },
        {
            Type = NoAction,
            Weighting = 9, },
    },
    BeingAttackedActions = {},
    FiringActions = {}, }
```
What I want is to put closing bracket for each table to new line.
Is there a way to force formatter to make it look like this:
```lua
Data = {
    howToBreakFormation = BreakImmediately,
    faceTargetHorizontal = 1,
    faceTargetVertical = 0,
    RandomActions =
    {
        {
            Type = PickNewTarget,
            Weighting = 1,
        },
        {
            Type = NoAction,
            Weighting = 9,
        },
    },
    BeingAttackedActions = {},
    FiringActions = {},
}
```

**Comment by CppCXY** [comment]
Without this feature, the  formatting would respect the original layout as much as possible. If you want this feature, please describe its specific principles

**Comment by Real-Gecko** [comment]
Put `table` closing bracket on a new line if it's opening bracket is not on the same line.

I guess that's the best I can formulate this.

By the way I've noticed that opening bracket is put on the same line as `=` only for "parent" table element, but not for nested.

https://user-images.githubusercontent.com/2231969/179153066-041b4aed-d4b3-4953-9210-fb2b9dbef0e3.mp4

Is this by design? Can it be configured too?

**Comment by CppCXY** [comment]
I didn't notice this, inside my algorithm I differentiate between two layout elements, here I use elements that don't allow line breaks. I would change to element that allows line breaks

**Comment by CppCXY** [comment]
all feature completed. 
this behavior is not an option but the default behavior.
the principles is that if the opening bracket and the table content are not on the same line, the closing bracket automatically chop down.
wait for sumneko next release. get this update

**Comment by Real-Gecko** [comment]
Thank you very much for your effort! Much appreciated!
