### ISSUE TITLE
[Feature request] Add support for insert_final_newline

### ISSUE THREAD

**Issue by gutyina70** [CppCXY/EmmyLuaCodeStyle#55]
This option should be a boolean value. When it's true, after trimming all the empty lines at the end of a file, one empty line should be inserted. When it's false, trim all empty lines at the end.

**Comment by CppCXY** [comment]
by default, my algorithm cleans up all trailing empty lines only keep one empty line, so you want no empty lines?

**Comment by CppCXY** [comment]
feature complete, wait for next release

**Comment by gutyina70** [comment]
You are right, your formatter does keep one line at the end. After researching on this topic a little bit, I found out some editor render trailing lines by default, and some don't.

![2022-07-23_18-06](https://user-images.githubusercontent.com/29818440/180613288-9807ecb2-5ce6-4493-8623-8d6be9fae308.png)

Thanks for adding the opposite of this feature anyway, I'm sure it will be useful for someone!
