### ISSUE TITLE
缩进修改非4个空格不生效。

### ISSUE THREAD

**Issue by Gowa2017** [CppCXY/EmmyLuaCodeStyle#62]
使用的是neovim。
单双引号都生效，但是缩进就不生效。

**Comment by CppCXY** [comment]
你使用得肯定不是我得本插件，sumneko 认为语言服务上得格式化算法应该遵守语言服务得规定，采用语言服务得缩进参数

**Comment by CppCXY** [comment]
于是对当前文件的格式化的缩进采用的是编辑器对当前文件的缩进认定

**Comment by Gowa2017** [comment]
> 你使用得肯定不是我得本插件，sumneko 认为语言服务上得格式化算法应该遵守语言服务得规定，采用语言服务得缩进参数

用的是 sumnko 语言服务器上面的。

**Comment by CppCXY** [comment]
语言服务的缩进参数通常来自编辑器本身的设置,所以改改编辑器的统一缩进

**Comment by Gowa2017** [comment]
我改了neovim设置，再次重启后行了。
