### ISSUE TITLE
editorconfig file fully cancels Lua.format.defaultConfig

### ISSUE THREAD

**Issue by ltWolfik** [CppCXY/EmmyLuaCodeStyle#63]
I've noticed, that `Lua.format.defaultConfig` setting works fine if `.editorconfig` absents, but if `.editorconfig` exists in project - `Lua.format.defaultConfig` does nothing. It seems be better if `Lua.format.defaultConfig` would be merged with `.editorconfig` (with priority for `.editorconfig`). 
For example, if `.editorconfig` does not have `keep_one_space_between_table_and_bracket` option - then use the same one from `Lua.format.defaultConfig` (if present).

I use the formatter through sumneko LSP in vscode. Thanks a lot.

**Comment by tomasklaen** [comment]
A little off topic, but there's no discussions and I don't want to make a new issue for this.

How do you set up `defaultConfig`? I added this to vscode's `User/settings.json`:

```json
"Lua.format.defaultConfig": {
	"indent_style": "tab",
	"tab_width": "4"
}
```

And it had no effect.

**Comment by ltWolfik** [comment]
@tomasklaen, maybe conflict with native vscode settings? Like the following:
```json
"[lua]": {
    "editor.insertSpaces": false,
    "editor.tabSize": 4
},
```

**Comment by CppCXY** [comment]
`Lua.format.defaultConfig` only valid for sumneko lua plugin.
in sumneko, the language server protocol should be respected, so indentation use the parameters of the LSP

**Comment by tomasklaen** [comment]
I am using sumneko's lua plugin, but I'm using EmmyLuaCodeStyle to format the code because sumneko's formatter ignores some editorconfig properties.

Is there no way to make these 2 work together?

I've tried adding this to `Lua.format.defaultConfig`:

```json
"insertSpaces": "false",
"tabSize": "4",
```

And this to `[lua]`:

```json
"editor.insertSpaces": false,
"editor.tabSize": 4
```

And again, no effect. Can someone just give me a snippet or some example/documentation somewhere how to configure the default formatting options? 😢

**Comment by CppCXY** [comment]
sumneko formatter is my formatter. but my plugin not support `Lua.format.defaultConfig` or editor settings. it only read .editorconfig plugin. 
You can set the formatter to sumneko lua because that's what I provide

**Comment by tomasklaen** [comment]
@CppCXY I'm using this one instead of sumneko's on [your own recomendation](https://github.com/sumneko/lua-language-server/issues/1495#issuecomment-1225624040) :) So the linked issue has been resolved, and sumneko now reads indentation style from editorconfig instead of user settings?

**Comment by CppCXY** [comment]
no, for sumneko, Indentation comes from editor settings, you can set editor setting for indentation

**Comment by CppCXY** [comment]
Sumnkeo has already been updated to the latest version, so the functionality is consistent
