### ISSUE TITLE
Improve formatting when line-breaking

### ISSUE THREAD

**Issue by FlashHit** [CppCXY/EmmyLuaCodeStyle#67]
If there is a max line-length it breaks the line in a not optimal way.

Example
```lua
local s_Guids = { Guid("0000-0000-0000-000000"), Guid("0000-0000-0000-000000") }
```

there would be cases where it would do:
```lua
local s_Guids = { Guid("0000-0000-0000-000000")
    , Guid("0000-0000-0000-000000") }
```

Instead, if it has to create a line break or if there exists a line break already, it should do: 
```lua
local s_Guids = {
    Guid("0000-0000-0000-000000"),
    Guid("0000-0000-0000-000000")
}
```

**Comment by CppCXY** [comment]
Maybe I should provide a preference series option, what name do you want to give this option

**Comment by FlashHit** [comment]
What name did it get?

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLuaCodeStyle/blob/26f24fc7ab0582ee6192fca4b10c6cb25b17be5d/lua.template.editorconfig#L121
