### ISSUE TITLE
If statements in multiple lines

### ISSUE THREAD

**Issue by FlashHit** [CppCXY/EmmyLuaCodeStyle#68]
Currently the formatter would do it like this:
```lua
if s_whatevercheck and
    s_whatevercheck2 and
    s_whatevercheck3 then
    s_whatevervar = false
end
```

instead I would prefer sth like this:
```lua
if s_whatevercheck and
s_whatevercheck2 and
s_whatevercheck3 then
    s_whatevervar = false
end
```

I just want to see where the if statement ends in a better way. Let me know what you think or if you have a better suggestion.

**Comment by CppCXY** [comment]
I think this is a good choice
```lua
if  s_whatevercheck
and s_whatevercheck2
and s_whatevercheck3 then
    s_whatevervar = false
end
```
if option `if_condition_align_with_each_other` is true, you can also choose to format as above.
Or
```lua
if     s_whatevercheck
and    s_whatevercheck2
and    s_whatevercheck3 then
    s_whatevervar = false
elseif s_aaaaaaa == b then

end
```

**Comment by CppCXY** [comment]
I mean that's what the existing option does, it's not the planning option

**Comment by FlashHit** [comment]
well the issue is that it also adds more spaces, which I don't like.
![grafik](https://user-images.githubusercontent.com/56718716/201873834-706cec99-9f18-48d7-a6d4-6bc632ad7fbb.png)

so instead of this:
```lua
if s_whatevercheck
    and s_whatevercheck2
    and s_whatevercheck3 then
    s_whatevervar = false
end
```
 or this:
```lua
if  s_whatevercheck
and s_whatevercheck2
and s_whatevercheck3 then
    s_whatevervar = false
end
```

if want this:
```lua
if s_whatevercheck
and s_whatevercheck2
and s_whatevercheck3 then
    s_whatevervar = false
end
```

**Comment by CppCXY** [comment]
The preset options are not what you would like，then wait for my refactoring, or you modify my code

**Comment by CppCXY** [comment]
ok, I forget, the option `if_condition_no_continuation_indent=true` may help, and remove option `if_condition_align_with_each_other=true`
