### ISSUE TITLE
Allow arbitrary spacing inside function calls

### ISSUE THREAD

**Issue by mawkler** [CppCXY/EmmyLuaCodeStyle#69]
Hi! I would like to be able to align the arguments of multiple similar function calls. Here's an example:

```lua
map('n',        '<C-j>',   quickfix_step('below'), { buffer = true })
map('n',        '<C-k>',   quickfix_step('above'), { buffer = true })
map('n',        '<Space>', '<CR><C-w>p',           { buffer = true })
map({'n', 'x'}, '<CR>',    '<CR>',                 { buffer = true })
```

Currently when I run the formatting it is changed to this:

```lua
map('n', '<C-j>', quickfix_step('below'), { buffer = true })
map('n', '<C-k>', quickfix_step('above'), { buffer = true })
map('n', '<Space>', '<CR><C-w>p', { buffer = true })
map({'n', 'x'}, '<CR>', '<CR>', { buffer = true })
```

Is it possible to tell the formatter not to touch the spaces inside function calls?

**Comment by CppCXY** [comment]
currently not, but I'm refactoring code. want to make it possible.

**Comment by CppCXY** [comment]
If my formatter doesn't satisfy you, you can use `---@format disable` inside the statement block, disable formatting within the current statement block. eg:
```
function f()
    ---@format disable
    map('n',        '<C-j>',   quickfix_step('below'), { buffer = true }) 
    map('n',        '<C-k>',   quickfix_step('above'), { buffer = true })
    map('n',        '<Space>', '<CR><C-w>p',           { buffer = true })
    map({'n', 'x'}, '<CR>',    '<CR>',                 { buffer = true })
end
```

**Comment by melkster** [comment]
Ok thank you. I look forward to the refactoring!

**Comment by CppCXY** [comment]
see #80 similar feature is complete.
but what are the principles for recognizing your needs?
for eg. different function call
```lua
p(1, 2, 3)
ppppp(1, 2, 3)
```
different but similar length
```lua
aaa(1, 2, 3)
bbb(1, 2, 3)
```
or only same function call
```lua
map(1, 2, 3)
map(4, 5, 6)
```

**Comment by mawkler** [comment]
@CppCXY To me it's enough if I could just tell EmmyLua not to modify the spacing between function arguments. Are you saying that #80 should support that now?

**Comment by CppCXY** [comment]
> @CppCXY To me it's enough if I could just tell EmmyLua not to modify the spacing between function arguments. Are you saying that #80 should support that now?

yes

**Comment by mawkler** [comment]
Awesome, thank you!
