### ISSUE TITLE
如何全局配置?

### ISSUE THREAD

**Issue by xiangnanscu** [CppCXY/EmmyLuaCodeStyle#70]
我有很多lua项目,如果每个地方都放相同的.editorconfig好像不太方便. 能否当前目录和~目录都能放置此配置文件, 且当前目录的配置优先

**Comment by CppCXY** [comment]
你如果使用的sumneko lua 那么Lua.format.defautConfig 可以全局配置具体看他的wiki https://github.com/sumneko/lua-language-server/wiki/Formatter

**Comment by CppCXY** [comment]
但是由于sumneko的偏好，缩进是无法在这里设置的，它依据的是编辑器的缩进设置，所以缩进得去编辑器相关设置设定
