### ISSUE TITLE
可以输出如下差异化的代码吗

### ISSUE THREAD

**Issue by qinyaoTAT** [CppCXY/EmmyLuaCodeStyle#71]
![image](https://user-images.githubusercontent.com/30612732/200492041-c5eec10b-b3df-4184-923e-0b41459bd740.png)

**Comment by CppCXY** [comment]
工具虽然会分析差异,但是分析的粒度更细, 更粗到单行或者几行的差异很难做.现成的方案就是拿到格式化后的文本和格式化前的文本使用diff比较

**Comment by qinyaoTAT** [comment]
get
