### ISSUE TITLE
Linux 指定 .editorconfig 配置文件无效

### ISSUE THREAD

**Issue by qinyaoTAT** [CppCXY/EmmyLuaCodeStyle#73]
如图设置配置文件，行长度设置为10：

![image](https://user-images.githubusercontent.com/30612732/203940070-1b962db0-29e2-4ef9-be39-fdcb16a85b50.png)

查看格式化后的LUA文件未生效

![image](https://user-images.githubusercontent.com/30612732/203939713-971313ab-68ce-4c37-8ffc-5d1a052c9669.png)

使用参数 -c 指定仍无效

但同样的测试Windows生效

**Comment by CppCXY** [comment]
我看看

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/203945579-1ba386ce-d88d-45a5-b01b-b9e85d627cd8.png)
我试过了没啥问题

**Comment by qinyaoTAT** [comment]
我刚才重新测试了 ，centos 确实生效了，之前我实在Ubuntu测试的，那就是在Ubuntu上的兼容问题

**Comment by CppCXY** [comment]
如果是这样你依然可以通过命令行指定参数

**Comment by CppCXY** [comment]
--max_line_width=10

**Comment by qinyaoTAT** [comment]
get
