### ISSUE TITLE
`insert_final_newline` doesn't work in Neovim

### ISSUE THREAD

**Issue by Fau818** [CppCXY/EmmyLuaCodeStyle#76]
`insert_final_newline` doesn't work in Neovim.

I use the newest neovim version.

**Comment by CppCXY** [comment]
有人说过这个问题，是neovim 无法显示 这个空行

**Comment by CppCXY** [comment]
#55

**Comment by Fau818** [comment]
> 有人说过这个问题，是neovim 无法显示 这个空行

感谢回复. 也就是说这个问题在Neovim中也没法解决?

**Comment by CppCXY** [comment]
如果是lsp导致的末尾空行的问题，你可以试试命令行版本，看看是不是依然这个问题
 release 里面可下

**Comment by Fau818** [comment]
我刚仔细看了看#55, 也明白您指的"无法显示"了.

**Comment by Fau818** [comment]
我刚刚仔细看了下#55, 明白您说的"无法显示这个空行"的意思了.

**Comment by Fau818** [comment]
我刚刚仔细看了下#55, 明白您说的"无法显示这个空行"的意思了.

我认为这个问题已经解决了, 感谢您宝贵的回复!

**Comment by Fau818** [comment]
Note: The reason why blank lines at the end of the file are not displayed is related to Neovim's handling of EOL.

https://www.reddit.com/r/neovim/comments/vzq7js/neovim_not_showing_the_last_blank_line/
