### ISSUE TITLE
'auto' is not a valid value in the editorconfig spec for end_of_line

### ISSUE THREAD

**Issue by craigmac** [CppCXY/EmmyLuaCodeStyle#81]
https://github.com/CppCXY/EmmyLuaCodeStyle/blob/ec2cd0e2cca3b1fa2e08c8bc8d146afd1bdfba19/lua.template.editorconfig#L19

Ran into this issue when testing out neovim nightly build which now ships with editorconfig support built-in: https://github.com/neovim/neovim/issues/21669

**Comment by CppCXY** [comment]
'auto' is a very meaningful option, but it is not an option specified by editorconfig, so what you want to do?
the short-term solution to this problem is to remove the definition of `end_of_line` because the default value is auto

**Comment by craigmac** [comment]
I agree it's a meaningful option, and wish that it was supported everywhere, and it's great that you do. However, unless you state this front-and-centre somewhere you're going to get more issues about this as people copy and paste the default config and expect it to work with Neovim out of the box. I think at least a big warning about it in the file would suffice!

**Comment by CppCXY** [comment]
I agree

**Comment by CppCXY** [comment]
have add note for this option https://github.com/CppCXY/EmmyLuaCodeStyle/blob/9ffcbcb75b2345922f1e2e2f6c31fba4ff2b1957/lua.template.editorconfig#L19
