### ISSUE TITLE
[Feature request] space_before_function_open_braces option that controls spaces before curly braces in function calls

### ISSUE THREAD

**Issue by ArmoredPony** [CppCXY/EmmyLuaCodeStyle#83]
If `space_before_function_open_parenthesis` parameter is set to `false` then `f (...)` call is formatted to `f(...)`. But curly braces are always formatted with space: `f {...}`. Would be nice to control this space presence with the same option or with a new one, like `space_before_function_open_braces`.

**Comment by CppCXY** [comment]
The reason single-parameter calls are uncontrolled is that for consecutive calls, spaces must be kept between them, for eg.
```lua
p "12313" "12313131" { aaa = bbb }
```
Probably you just hope:
```lua
p{ a = 123 } "123131" "4665465"
```

**Comment by ArmoredPony** [comment]
But if we call function not with curly braces but parentheses, then there will be no space after function name, considering `space_before_function_open_parenthesis` is `false`. If I use parenthesis in consecutive calls then it would look like this: `p(var) '123' '456'` which looks similar to `p{a = 123} "123131" "4665465"`. Why curly braces should be treated differently than parentheses in terms of formatting?

**Comment by CppCXY** [comment]
their grammatical components are different, and this feature(space_before_function_open_parenthesis) was originally added by other contributor.
If you want to implement this feature, you can think of a name

**Comment by CppCXY** [comment]
I decided to implement this feature before the 1.0.0 release

**Comment by CppCXY** [comment]
feature complete, option name is `space_before_function_call_single_arg`

**Comment by ArmoredPony** [comment]
I love how this feature works with tables, but I would gladly disable it when it comes to strings. In SpaceAnalyzer.cpp, I tried to implement this myself by catching curly brace at [this](https://github.com/CppCXY/EmmyLuaCodeStyle/blob/f1254035d82508653215f4f21cb3168c7ac57f14/CodeService/src/Format/Analyzer/SpaceAnalyzer.cpp#L161) `else` branch with something like `GetChildToken('{', t)`, however I appear to be not competent enough to comprehend your parser and implement my idea. Would you please consider reopening the request and splitting this feature into two: `space_before_function_call_single_table` for tables and `space_before_function_call_single_string` for strings?

**Comment by CppCXY** [comment]
if you want to develop this project, please see `test2`, this will print lua syntax tree. And this feature has been completed `space_before_function_call_single_arg=only_string`
