### ISSUE TITLE
使用CodeFormat.exe的问题

### ISSUE THREAD

**Issue by huyi51462** [CppCXY/EmmyLuaCodeStyle#85]
使用CodeFormat.exe格式化代码,总是不能正确读取配置文件
看了一下源码,想问问大佬:
EmmyLuaCodeStyle\CodeFormat\src\LuaFormat.cpp 这个文件里的 GetStyle 函数
这个函数里面的 std::size_t matchProcess 的用处是啥?我看赋值了也没用啊...
if (config.Workspace.size() > matchProcess) 这个判断导致不能读取给定的配置文件,总是读取_defaultStyle
是我参数没用对还是?

我使用的参数 
.\CodeFormat.exe format -f X:\XXXX.lua -c .\.editorconfig -ow
确认能够格式化文件,但是.editorconfig里面的配置不能生效.

```
LuaStyle LuaFormat::GetStyle(std::string_view path) {
    std::shared_ptr<LuaEditorConfig> editorConfig = nullptr;
    std::size_t matchProcess = 0;
    for (auto &config: _configs) {
        if (string_util::StartWith(path, config.Workspace)) {
            if (config.Workspace.size() > matchProcess) {
                matchProcess = config.Workspace.size();
                editorConfig = config.Editorconfig;
            }
        }
    }

    if (editorConfig) {
        return editorConfig->Generate(path);
    }
    return _defaultStyle;
}
```

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLuaCodeStyle/actions/runs/4180668691
等这里编译好了,试试看

**Comment by huyi51462** [comment]
> https://github.com/CppCXY/EmmyLuaCodeStyle/actions/runs/4180668691 等这里编译好了,试试看

好的
