### ISSUE TITLE
unable to select the lua code formatter

### ISSUE THREAD

**Issue by achidipothu** [CppCXY/EmmyLuaCodeStyle#86]
Hello,

I installed [emmylua-codestyle](https://marketplace.visualstudio.com/items?itemName=CppCXY.emmylua-codestyle) along with [sumneko.lua](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) Lua language server.

Now I intend to use the emmylua as the default code formatter. However I dont get the option to select it. I only get to select the default formatter provided by the sumneko. 

![image](https://user-images.githubusercontent.com/98626213/219271597-dfbff7a4-b4f6-4cbb-b008-99a33a798679.png)

Thanks in advance.

**Comment by CppCXY** [comment]
sumneko lua use this repo as formatter, why install my plugin

**Comment by CppCXY** [comment]
I accept many report , can not active my plugin. maybe this is a bug

**Comment by CppCXY** [comment]
It's a bug of vscode-language-server 8.1.0 , new version has release

**Comment by achidipothu** [comment]
updated to the latest vscode 1.75.1 thanks.
