### ISSUE TITLE
space_before_function_open_parenthesis doesnt work.

### ISSUE THREAD

**Issue by achidipothu** [CppCXY/EmmyLuaCodeStyle#87]
The setting "space_before_function_open_parenthesis" that was introduced in [issue#52](https://github.com/CppCXY/EmmyLuaCodeStyle/issues/52) doesn't seem to work now.

I am using the .editorconfig

**Comment by achidipothu** [comment]
it is even showing squiggles against the setting.

![image](https://user-images.githubusercontent.com/98626213/219578056-e62a1ab1-c112-432a-af13-5e28123b693c.png)

**Comment by CppCXY** [comment]
not this option, it is `space_before_function_call_open_parenthesis`

**Comment by CppCXY** [comment]
this option is subdivided into a number of options, it is recommended to revisit the doc

**Comment by achidipothu** [comment]
ohh ok sure.

**Comment by achidipothu** [comment]
can u pls point me to the docs?

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/docs/format_config_EN.md

**Comment by achidipothu** [comment]
:pray:
