### ISSUE TITLE
Multiline closure body alignment in call arguments

### ISSUE THREAD

**Issue by ArmoredPony** [CppCXY/EmmyLuaCodeStyle#88]
If a multiline closure is a function call argument then its body gets formatted in a wierd way.
If `function ()` is not the first statement on the line then closure body is not indented enough:
```
debug.upvaluejoin(fn, i, function ()
  return env
end,
  1)
```
When `function ()` is on a separate line, the body is properly indented as long as `align_call_args` is false. If it's set to true, however, the closure body does not align with other arguments, it just gets indented by 2 additional spaces as if it would with `align_call_args` set to false:
```
debug.upvaluejoin(fn, i,
                  function ()
    return env
  end,
                  1)
```
If closure is a single line statement then it's formatted correctly. Seems like a bug to me.
<sub>also thank you for your hard work, your formatter makes my work much better ❤️</sub>

**Comment by CppCXY** [comment]
formatting is a very complex job, there are always many special cases to deal with
