### ISSUE TITLE
Table key/value format  error

### ISSUE THREAD

**Issue by AbaoFromCUG** [CppCXY/EmmyLuaCodeStyle#92]
# Env
neovim + lspconfig + lua_ls 

使用的是默认配置，没有在editorconfig中配置
// with default config

# 复现 // Recurrent
下面的代码格式化之后会保持原样，强制对其再次格式化会变成下面这样不对齐的样子
// the below code not format as expected

```lua
local test_table = {
    k = 'value1',
        ['?'] = 'value2',
    k2 = 'value1',
        [123] = 456,
    foo = 'bar',
}
```

Thinks:heart:

**Comment by CppCXY** [comment]
这个问题改过了

**Comment by AbaoFromCUG** [comment]
谢谢，我更新下lua_ls

**Comment by CppCXY** [comment]
他也没提交新版本, 先等几天吧

**Comment by AbaoFromCUG** [comment]
好的
