### ISSUE TITLE
Incompatible format warnings introduced with lua_ls `3.6.18`

### ISSUE THREAD

**Issue by ibhagwan** [CppCXY/EmmyLuaCodeStyle#99]
Hi again @CppCXY,

Ty for your hard work :-)

It seems that `3.6.18` introduced new warnings for something that was formatted by `3.6.17`, the formatter is expecting the below code to be indented by extra 2 whitespaces:
![image](https://user-images.githubusercontent.com/59988195/227718321-049553d5-1100-4cd3-937f-0842e0757c47.png)

If I add 2 new spaces the warnings will disappear but then when I run the auto-formatter again it will re-indent left which generates the warnings again:
![image](https://user-images.githubusercontent.com/59988195/227718410-6aaafc1c-182f-4a6f-a363-227679f289ff.png)

I'm not sure which one is wrong, the warnings or the formatter.

**Comment by CppCXY** [comment]
this must be a bug
